from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

def setupSpell(self):
    # tab
    self.tab1 = QtGui.QWidget()
    self.tab1.setObjectName(_fromUtf8("tab1"))
    self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab1)
    self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
    # spell tab
    self.tab1_spell_tab = QtGui.QTabWidget(self.tab1)
    self.tab1_spell_tab.setObjectName(_fromUtf8("tab1_spell_tab"))
    self.tab1_tab0 = QtGui.QWidget()
    self.tab1_tab0.setObjectName(_fromUtf8("tab1_tab0"))
    self.verticalLayout_9 = QtGui.QVBoxLayout(self.tab1_tab0)
    self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))

    # cantrip tab
    self.tab1_tab0_list_layout = QtGui.QGroupBox("List", self.tab1_tab0)
    self.tab1_tab0_list_layout.setObjectName(_fromUtf8("tab1_tab0_list_layout"))
    self.horizontalLayout_36 = QtGui.QHBoxLayout(self.tab1_tab0_list_layout)
    self.horizontalLayout_36.setObjectName(_fromUtf8("horizontalLayout_36"))
    # list
    self.tab1_tab0_list_tree = QtGui.QTreeWidget(self.tab1_tab0_list_layout)
    self.tab1_tab0_list_tree.setSortingEnabled(True)
    self.tab1_tab0_list_tree.currentItemChanged.connect(self.updateCantripDescription)
    self.tab1_tab0_list_tree.setObjectName(_fromUtf8("tab1_tab0_list_tree"))
    self.tab1_tab0_list_tree.headerItem().setText(0, "Name")
    self.tab1_tab0_list_tree.headerItem().setText(1, "Casting time")
    self.tab1_tab0_list_tree.headerItem().setText(2, "Range")
    self.tab1_tab0_list_tree.headerItem().setText(3, "Components")
    self.tab1_tab0_list_tree.headerItem().setText(4, "Duration")
    self.tab1_tab0_list_tree.headerItem().setText(5, "School")

    self.horizontalLayout_36.addWidget(self.tab1_tab0_list_tree)
    self.verticalLayout_9.addWidget(self.tab1_tab0_list_layout)
    self.tab1_tab0_button_layout = QtGui.QHBoxLayout()
    self.tab1_tab0_button_layout.setContentsMargins(-1, 0, -1, -1)
    self.tab1_tab0_button_layout.setObjectName(_fromUtf8("tab1_tab0_button_layout"))
    self.tab1_tab0_class_label = QtGui.QLabel("Spell Class", self.tab1_tab0)
    self.tab1_tab0_button_layout.addWidget(self.tab1_tab0_class_label)
        
    self.tab1_tab0_class_combo = QtGui.QComboBox(self.tab1_tab0)
    self.tab1_tab0_class_combo.setObjectName(_fromUtf8("tab1_tab0_class_combo"))
    self.tab1_tab0_button_layout.addWidget(self.tab1_tab0_class_combo)
    self.tab1_tab0_class_combo.addItem("Any")
    for i in self.class_parser.getListClass():
        self.tab1_tab0_class_combo.addItem(i)
    self.tab1_tab0_class_combo.activated[str].connect(self.selectClassSpell)

    self.tab1_tab0_add_button = QtGui.QPushButton("Add", self.tab1_tab0)
    self.tab1_tab0_add_button.setObjectName(_fromUtf8("tab1_tab0_add_button"))
    self.tab1_tab0_add_button.clicked.connect(self.addCantrip)
    self.tab1_tab0_button_layout.addWidget(self.tab1_tab0_add_button)
    self.tab1_tab0_remove_button = QtGui.QPushButton("Remove", self.tab1_tab0)
    self.tab1_tab0_remove_button.setObjectName(_fromUtf8("tab1_tab0_remove_button"))
    self.tab1_tab0_remove_button.clicked.connect(self.removeCantrip)
    self.tab1_tab0_button_layout.addWidget(self.tab1_tab0_remove_button)
    self.verticalLayout_9.addLayout(self.tab1_tab0_button_layout)
    self.tab1_tab0_lower_layout = QtGui.QHBoxLayout()
    self.tab1_tab0_lower_layout.setObjectName(_fromUtf8("tab1_tab0_lower_layout"))
    # known
    self.tab1_tab0_know_layout = QtGui.QGroupBox("Known", self.tab1_tab0)
    self.tab1_tab0_know_layout.setObjectName(_fromUtf8("tab1_tab0_know_layout"))
    self.verticalLayout_11 = QtGui.QVBoxLayout(self.tab1_tab0_know_layout)
    self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
    self.tab1_tab0_known_tree = QtGui.QTreeWidget(self.tab1_tab0_know_layout)
    self.tab1_tab0_known_tree.setSortingEnabled(True)
    self.tab1_tab0_known_tree.setObjectName(_fromUtf8("tab1_tab0_known_tree"))
    self.tab1_tab0_known_tree.headerItem().setText(0, "Name")
    self.tab1_tab0_known_tree.headerItem().setText(1, "Casting time")
    self.tab1_tab0_known_tree.headerItem().setText(2, "Range")
    self.tab1_tab0_known_tree.headerItem().setText(3, "Components")
    self.tab1_tab0_known_tree.headerItem().setText(4, "Duration")
    self.tab1_tab0_known_tree.headerItem().setText(5, "School")
    self.tab1_tab0_known_tree.currentItemChanged.connect(self.updateCantripDescription)

    self.verticalLayout_11.addWidget(self.tab1_tab0_known_tree)
    self.tab1_tab0_lower_layout.addWidget(self.tab1_tab0_know_layout)
    self.tab1_tab0_description = QtGui.QTextBrowser(self.tab1_tab0)
    self.tab1_tab0_description.setObjectName(_fromUtf8("tab1_tab0_description"))
    self.tab1_tab0_lower_layout.addWidget(self.tab1_tab0_description)
    self.verticalLayout_9.addLayout(self.tab1_tab0_lower_layout)
    self.tab1_tab0_available_label = QtGui.QLabel("Cantrip known: 4/6", self.tab1_tab0)
    self.tab1_tab0_available_label.setAlignment(QtCore.Qt.AlignCenter)
    self.tab1_tab0_available_label.setObjectName(_fromUtf8("tab1_tab0_available_label"))
    self.verticalLayout_9.addWidget(self.tab1_tab0_available_label)
    self.tab1_spell_tab.addTab(self.tab1_tab0, "Cantrips")

    # Spells
    self.tab1_tab1 = QtGui.QWidget()
    self.tab1_tab1.setObjectName(_fromUtf8("tab1_tab1"))
    self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab1_tab1)
    self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
    # list
    self.tab1_tab1_list_layout = QtGui.QGroupBox("List", self.tab1_tab1)
    self.tab1_tab1_list_layout.setObjectName(_fromUtf8("tab1_tab1_list_layout"))
    self.horizontalLayout_7 = QtGui.QHBoxLayout(self.tab1_tab1_list_layout)
    self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
    self.tab1_tab1_list_tree = QtGui.QTreeWidget(self.tab1_tab1_list_layout)
    self.tab1_tab1_list_tree.setSortingEnabled(True)
    self.tab1_tab1_list_tree.setObjectName(_fromUtf8("tab1_tab1_list_tree"))
    self.tab1_tab1_list_tree.headerItem().setText(0, "Name")
    self.tab1_tab1_list_tree.headerItem().setText(1, "Casting Time")
    self.tab1_tab1_list_tree.headerItem().setText(2, "Range")
    self.tab1_tab1_list_tree.headerItem().setText(3, "Components")
    self.tab1_tab1_list_tree.headerItem().setText(4, "Duration")
    self.tab1_tab1_list_tree.headerItem().setText(5, "School")
    self.tab1_tab1_list_tree.currentItemChanged.connect(self.updateSpellDescription)

        
    self.horizontalLayout_7.addWidget(self.tab1_tab1_list_tree)
    self.verticalLayout_5.addWidget(self.tab1_tab1_list_layout)
    self.tab1_tab1_button_layout = QtGui.QHBoxLayout()
    self.tab1_tab1_button_layout.setContentsMargins(-1, 0, -1, -1)
    self.tab1_tab1_button_layout.setObjectName(_fromUtf8("tab1_tab1_button_layout"))
    self.tab1_tab1_class_label = QtGui.QLabel("Spell Class", self.tab1_tab1)
    self.tab1_tab1_button_layout.addWidget(self.tab1_tab1_class_label)
        
    self.tab1_tab1_class_combo = QtGui.QComboBox(self.tab1_tab1)
    self.tab1_tab1_class_combo.setObjectName(_fromUtf8("tab1_tab1_class_combo"))
    self.tab1_tab1_button_layout.addWidget(self.tab1_tab1_class_combo)
    self.tab1_tab1_class_combo.addItem("Any")
    for i in self.class_parser.getListClass():
        self.tab1_tab1_class_combo.addItem(i)
    self.tab1_tab1_class_combo.activated[str].connect(self.selectClassSpell)

    self.tab1_tab1_add_button = QtGui.QPushButton("Add", self.tab1_tab1)
    self.tab1_tab1_add_button.setObjectName(_fromUtf8("tab1_tab1_add_button"))
    self.tab1_tab1_add_button.clicked.connect(self.addSpell)
    self.tab1_tab1_button_layout.addWidget(self.tab1_tab1_add_button)
    self.tab1_tab1_remove_button = QtGui.QPushButton("Remove", self.tab1_tab1)
    self.tab1_tab1_remove_button.setObjectName(_fromUtf8("tab1_tab1_remove_button"))
    self.tab1_tab1_remove_button.clicked.connect(self.removeSpell)
    self.tab1_tab1_button_layout.addWidget(self.tab1_tab1_remove_button)
    self.verticalLayout_5.addLayout(self.tab1_tab1_button_layout)
    self.tab1_tab1_lower_layout = QtGui.QHBoxLayout()
    self.tab1_tab1_lower_layout.setObjectName(_fromUtf8("tab1_tab1_lower_layout"))
    # known
    self.tab1_tab1_known_layout = QtGui.QGroupBox("Known", self.tab1_tab1)
    self.tab1_tab1_known_layout.setObjectName(_fromUtf8("tab1_tab1_known_layout"))
    self.horizontalLayout_8 = QtGui.QHBoxLayout(self.tab1_tab1_known_layout)
    self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
    self.tab1_tab1_known_tree = QtGui.QTreeWidget(self.tab1_tab1_known_layout)
    self.tab1_tab1_known_tree.setSortingEnabled(True)
    self.tab1_tab1_known_tree.setObjectName(_fromUtf8("tab1_tab1_known_tree"))
    self.tab1_tab1_known_tree.headerItem().setText(0, _fromUtf8("Name"))
    self.horizontalLayout_8.addWidget(self.tab1_tab1_known_tree)
    self.tab1_tab1_lower_layout.addWidget(self.tab1_tab1_known_layout)
    self.tab1_tab1_known_tree.headerItem().setText(1, "Casting time")
    self.tab1_tab1_known_tree.headerItem().setText(2, "Range")
    self.tab1_tab1_known_tree.headerItem().setText(3, "Components")
    self.tab1_tab1_known_tree.headerItem().setText(4, "Duration")
    self.tab1_tab1_known_tree.headerItem().setText(4, "School")
    self.tab1_tab1_known_tree.currentItemChanged.connect(self.updateSpellDescription)
        
    self.tab1_tab1_description = QtGui.QTextBrowser(self.tab1_tab1)
    self.tab1_tab1_description.setObjectName(_fromUtf8("tab1_tab1_description"))
    self.tab1_tab1_lower_layout.addWidget(self.tab1_tab1_description)
    self.verticalLayout_5.addLayout(self.tab1_tab1_lower_layout)
    self.tab1_tab1_available_label = QtGui.QLabel("Spells known: 4/5", self.tab1_tab1)
    self.tab1_tab1_available_label.setAlignment(QtCore.Qt.AlignCenter)
    self.tab1_tab1_available_label.setObjectName(_fromUtf8("tab1_tab1_available_label"))
    self.verticalLayout_5.addWidget(self.tab1_tab1_available_label)
    self.tab1_spell_tab.addTab(self.tab1_tab1, "Spells")    

    self.selectClassSpell('any')
    self.verticalLayout_3.addWidget(self.tab1_spell_tab)
    self.main_tab.addTab(self.tab1, "Spells")

