from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s
        
def setupEquipment(self):
    self.tab6 = QtGui.QWidget()
    self.tab6.setObjectName(_fromUtf8("tab6"))
    self.verticalLayout_6 = QtGui.QVBoxLayout(self.tab6)
    self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
    self.tab6_tabwidget = QtGui.QTabWidget(self.tab6)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.tab6_tabwidget.sizePolicy().hasHeightForWidth())
    self.tab6_tabwidget.setSizePolicy(sizePolicy)
    self.tab6_tabwidget.setObjectName(_fromUtf8("tab6_tabwidget"))

    # weapons
    self.tab6_tab0 = QtGui.QWidget()
    self.tab6_tab0.setObjectName(_fromUtf8("tab6_tab0"))
    self.horizontalLayout_11 = QtGui.QHBoxLayout(self.tab6_tab0)
    self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
    # list
    self.tab6_tab0_list_layout = QtGui.QGroupBox("List", self.tab6_tab0)
    self.tab6_tab0_list_layout.setObjectName(_fromUtf8("tab6_tab0_list_layout"))
    self.horizontalLayout_31 = QtGui.QHBoxLayout(self.tab6_tab0_list_layout)
    self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
    self.tab6_tab0_list_tree = QtGui.QTreeWidget(self.tab6_tab0_list_layout)
    self.tab6_tab0_list_tree.setRootIsDecorated(True)
    self.tab6_tab0_list_tree.setObjectName(_fromUtf8("tab6_tab0_list_tree"))
    item_0 = QtGui.QTreeWidgetItem(self.tab6_tab0_list_tree)
    item_0 = QtGui.QTreeWidgetItem(self.tab6_tab0_list_tree)
    item_1 = QtGui.QTreeWidgetItem(item_0)
    item_0 = QtGui.QTreeWidgetItem(self.tab6_tab0_list_tree)
    item_0 = QtGui.QTreeWidgetItem(self.tab6_tab0_list_tree)
    self.horizontalLayout_31.addWidget(self.tab6_tab0_list_tree)
    self.horizontalLayout_11.addWidget(self.tab6_tab0_list_layout)
    self.tab6_tab0_list_tree.setSortingEnabled(True)
    self.tab6_tab0_list_tree.headerItem().setText(0, "Name")
    self.tab6_tab0_list_tree.headerItem().setText(1, "Cost")
    self.tab6_tab0_list_tree.headerItem().setText(2, "Damage")
    self.tab6_tab0_list_tree.headerItem().setText(3, "Weight")
    self.tab6_tab0_list_tree.headerItem().setText(4, "Properties")
    __sortingEnabled = self.tab6_tab0_list_tree.isSortingEnabled()
    self.tab6_tab0_list_tree.setSortingEnabled(False)
    self.tab6_tab0_list_tree.topLevelItem(1).setText(0, "Simple Melee Weapons")
    self.tab6_tab0_list_tree.topLevelItem(1).child(0).setText(0, "Club")
    self.tab6_tab0_list_tree.topLevelItem(1).child(0).setText(1, "1sp")
    self.tab6_tab0_list_tree.topLevelItem(1).child(0).setText(2, "1d4 Bludgeoning")
    self.tab6_tab0_list_tree.topLevelItem(1).child(0).setText(3, "2lb.")
    self.tab6_tab0_list_tree.topLevelItem(1).child(0).setText(4, "Light")
    self.tab6_tab0_list_tree.setSortingEnabled(__sortingEnabled)
    # owned
    self.tab6_tab0_owned_layout = QtGui.QGroupBox("Owned", self.tab6_tab0)
    self.tab6_tab0_owned_layout.setObjectName(_fromUtf8("tab6_tab0_owned_layout"))
    self.horizontalLayout_32 = QtGui.QHBoxLayout(self.tab6_tab0_owned_layout)
    self.horizontalLayout_32.setObjectName(_fromUtf8("horizontalLayout_32"))
    self.tab6_tab0_owned_tree = QtGui.QTreeWidget(self.tab6_tab0_owned_layout)
    self.tab6_tab0_owned_tree.setObjectName(_fromUtf8("tab6_tab0_owned_tree"))
    self.horizontalLayout_32.addWidget(self.tab6_tab0_owned_tree)
    self.horizontalLayout_11.addWidget(self.tab6_tab0_owned_layout)
    self.tab6_tab0_owned_layout.setTitle("Weapon Owned")
    self.tab6_tab0_owned_tree.headerItem().setText(0, "Name")
    self.tab6_tab0_owned_tree.headerItem().setText(1, "Cost")
    self.tab6_tab0_owned_tree.headerItem().setText(2, "Damage")
    self.tab6_tab0_owned_tree.headerItem().setText(3, "Weight")
    self.tab6_tab0_owned_tree.headerItem().setText(4, "Properties")
    self.tab6_tabwidget.addTab(self.tab6_tab0, "Weapons")
    
    # armor
    self.tab6_tab1 = QtGui.QWidget()
    self.tab6_tab1.setObjectName(_fromUtf8("tab6_tab1"))
    self.horizontalLayout_23 = QtGui.QHBoxLayout(self.tab6_tab1)
    self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
    # list
    self.tab6_tab1_list_layout = QtGui.QGroupBox("List", self.tab6_tab1)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.tab6_tab1_list_layout.sizePolicy().hasHeightForWidth())
    self.tab6_tab1_list_layout.setSizePolicy(sizePolicy)
    self.tab6_tab1_list_layout.setObjectName(_fromUtf8("tab6_tab1_list_layout"))
    self.horizontalLayout_29 = QtGui.QHBoxLayout(self.tab6_tab1_list_layout)
    self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
    self.tab6_tab1_list_tree = QtGui.QTreeWidget(self.tab6_tab1_list_layout)
    self.tab6_tab1_list_tree.setRootIsDecorated(True)
    self.tab6_tab1_list_tree.setObjectName(_fromUtf8("tab6_tab1_list_tree"))
    item_0 = QtGui.QTreeWidgetItem(self.tab6_tab1_list_tree)
    item_1 = QtGui.QTreeWidgetItem(item_0)
    item_1 = QtGui.QTreeWidgetItem(item_0)
    self.tab6_tab1_list_tree.setSortingEnabled(True)
    self.tab6_tab1_list_tree.headerItem().setText(0, "Name")
    self.tab6_tab1_list_tree.headerItem().setText(1, "Cost")
    self.tab6_tab1_list_tree.headerItem().setText(2, "Armor")
    self.tab6_tab1_list_tree.headerItem().setText(3, "Strength")
    self.tab6_tab1_list_tree.headerItem().setText(4, "Stealth")
    self.tab6_tab1_list_tree.headerItem().setText(5, "Weight")
    __sortingEnabled = self.tab6_tab1_list_tree.isSortingEnabled()
    self.tab6_tab1_list_tree.setSortingEnabled(False)
    self.tab6_tab1_list_tree.topLevelItem(0).setText(0, "Light Armor")
    self.tab6_tab1_list_tree.topLevelItem(0).child(0).setText(0, "Padded")
    self.tab6_tab1_list_tree.topLevelItem(0).child(0).setText(1, "5gp")
    self.tab6_tab1_list_tree.topLevelItem(0).child(0).setText(2, "11+Dex")
    self.tab6_tab1_list_tree.topLevelItem(0).child(0).setText(4, "Disadvantage")
    self.tab6_tab1_list_tree.topLevelItem(0).child(0).setText(5, "8lb.")
    self.tab6_tab1_list_tree.setSortingEnabled(__sortingEnabled)
    self.horizontalLayout_29.addWidget(self.tab6_tab1_list_tree)
    self.horizontalLayout_23.addWidget(self.tab6_tab1_list_layout)
    # owned
    self.tab6_tab1_owned_layout = QtGui.QGroupBox("Owned", self.tab6_tab1)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.tab6_tab1_owned_layout.sizePolicy().hasHeightForWidth())
    self.tab6_tab1_owned_layout.setSizePolicy(sizePolicy)
    self.tab6_tab1_owned_layout.setObjectName(_fromUtf8("tab6_tab1_owned_layout"))
    self.horizontalLayout_30 = QtGui.QHBoxLayout(self.tab6_tab1_owned_layout)
    self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
    self.tab6_tab1_owned_tree = QtGui.QTreeWidget(self.tab6_tab1_owned_layout)
    self.tab6_tab1_owned_tree.setObjectName(_fromUtf8("tab6_tab1_owned_tree"))
    self.tab6_tab1_owned_tree.headerItem().setText(0, "Name")
    self.tab6_tab1_owned_tree.headerItem().setText(1, "Cost")
    self.tab6_tab1_owned_tree.headerItem().setText(2, "Armor")
    self.tab6_tab1_owned_tree.headerItem().setText(3, "Strength")
    self.tab6_tab1_owned_tree.headerItem().setText(4, "Stealth")
    self.tab6_tab1_owned_tree.headerItem().setText(5, "Weight")
    self.horizontalLayout_30.addWidget(self.tab6_tab1_owned_tree)
    self.horizontalLayout_23.addWidget(self.tab6_tab1_owned_layout)
    self.tab6_tabwidget.addTab(self.tab6_tab1, "Armor")

    # Gear
    self.tab6_tab2 = QtGui.QWidget()
    self.tab6_tab2.setObjectName(_fromUtf8("tab6_tab2"))
    self.horizontalLayout_24 = QtGui.QHBoxLayout(self.tab6_tab2)
    self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
    # list
    self.tab6_tab2_list_layout = QtGui.QGroupBox("List", self.tab6_tab2)
    self.tab6_tab2_list_layout.setObjectName(_fromUtf8("tab6_tab2_list_layout"))
    self.horizontalLayout_28 = QtGui.QHBoxLayout(self.tab6_tab2_list_layout)
    self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
    self.tab6_tab2_list_tree = QtGui.QTreeWidget(self.tab6_tab2_list_layout)
    self.tab6_tab2_list_tree.setObjectName(_fromUtf8("tab6_tab2_list_tree"))
    item_0 = QtGui.QTreeWidgetItem(self.tab6_tab2_list_tree)
    item_0 = QtGui.QTreeWidgetItem(self.tab6_tab2_list_tree)
    item_1 = QtGui.QTreeWidgetItem(item_0)
    item_1 = QtGui.QTreeWidgetItem(item_0)
    item_1 = QtGui.QTreeWidgetItem(item_0)
    item_1 = QtGui.QTreeWidgetItem(item_0)
    item_1 = QtGui.QTreeWidgetItem(item_0)
    item_1 = QtGui.QTreeWidgetItem(item_0)
    item_1 = QtGui.QTreeWidgetItem(item_0)
    self.tab6_tab2_list_tree.headerItem().setText(0, "Name")
    self.tab6_tab2_list_tree.headerItem().setText(1, "Cost")
    self.tab6_tab2_list_tree.headerItem().setText(2, "Weight")
    self.tab6_tab2_list_tree.headerItem().setText(3, "Quantity")
    __sortingEnabled = self.tab6_tab2_list_tree.isSortingEnabled()
    self.tab6_tab2_list_tree.setSortingEnabled(False)
    self.tab6_tab2_list_tree.topLevelItem(0).setText(0, "Abacus")
    self.tab6_tab2_list_tree.topLevelItem(0).setText(1, "2gp")
    self.tab6_tab2_list_tree.topLevelItem(0).setText(2, "2lb.")
    self.tab6_tab2_list_tree.topLevelItem(1).setText(0, "Explorer\'s pack")
    self.tab6_tab2_list_tree.topLevelItem(1).setText(1, "10gp")
    self.tab6_tab2_list_tree.topLevelItem(1).child(0).setText(0, "Backpack")
    self.tab6_tab2_list_tree.topLevelItem(1).child(1).setText(0, "Bedroll")
    self.tab6_tab2_list_tree.topLevelItem(1).child(2).setText(0, "Mess kit")
    self.tab6_tab2_list_tree.topLevelItem(1).child(3).setText(0, "Tinderbox")
    self.tab6_tab2_list_tree.topLevelItem(1).child(4).setText(0, "Torche")
    self.tab6_tab2_list_tree.topLevelItem(1).child(4).setText(3, "10")
    self.tab6_tab2_list_tree.topLevelItem(1).child(5).setText(0, "Ration")
    self.tab6_tab2_list_tree.topLevelItem(1).child(5).setText(3, "10")
    self.tab6_tab2_list_tree.topLevelItem(1).child(6).setText(0, "Waterskin")
    self.tab6_tab2_list_tree.setSortingEnabled(__sortingEnabled)
    self.horizontalLayout_28.addWidget(self.tab6_tab2_list_tree)
    self.horizontalLayout_24.addWidget(self.tab6_tab2_list_layout)
    # owned
    self.tab6_tab2_owned_layout = QtGui.QGroupBox("Owned", self.tab6_tab2)
    self.tab6_tab2_owned_layout.setObjectName(_fromUtf8("tab6_tab2_owned_layout"))
    self.verticalLayout_23 = QtGui.QVBoxLayout(self.tab6_tab2_owned_layout)
    self.verticalLayout_23.setObjectName(_fromUtf8("verticalLayout_23"))
    self.tab6_tab2_owned_tree = QtGui.QTreeWidget(self.tab6_tab2_owned_layout)
    self.tab6_tab2_owned_tree.setObjectName(_fromUtf8("tab6_tab2_owned_tree"))
    self.tab6_tab2_owned_tree.headerItem().setText(0, "Name")
    self.tab6_tab2_owned_tree.headerItem().setText(1, "Cost")
    self.tab6_tab2_owned_tree.headerItem().setText(2, "Weight")
    self.tab6_tab2_owned_tree.headerItem().setText(3, "Quantity")
    self.verticalLayout_23.addWidget(self.tab6_tab2_owned_tree)
    self.horizontalLayout_24.addWidget(self.tab6_tab2_owned_layout)
    self.tab6_tabwidget.addTab(self.tab6_tab2, "Gear")

    # lower part
    self.verticalLayout_6.addWidget(self.tab6_tabwidget)
    self.tab6_gold_layout = QtGui.QHBoxLayout()
    self.tab6_gold_layout.setContentsMargins(0, 0, -1, -1)
    # money
    self.tab6_gold_layout.setObjectName(_fromUtf8("tab6_gold_layout"))
    spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
    self.tab6_gold_layout.addItem(spacerItem9)
    self.tab6_gold_label = QtGui.QLabel("1gp, 2sp, 1cp", self.tab6)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.tab6_gold_label.sizePolicy().hasHeightForWidth())
    self.tab6_gold_label.setSizePolicy(sizePolicy)
    self.tab6_gold_label.setAlignment(QtCore.Qt.AlignCenter)
    self.tab6_gold_label.setObjectName(_fromUtf8("tab6_gold_label"))
    self.tab6_gold_layout.addWidget(self.tab6_gold_label)
    spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
    self.tab6_gold_layout.addItem(spacerItem10)
    self.tab6_gold_button = QtGui.QPushButton("Earn/Loose Money", self.tab6)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.tab6_gold_button.sizePolicy().hasHeightForWidth())
    self.tab6_gold_button.setSizePolicy(sizePolicy)
    self.tab6_gold_button.setObjectName(_fromUtf8("tab6_gold_button"))
    self.tab6_gold_layout.addWidget(self.tab6_gold_button)
    self.verticalLayout_6.addLayout(self.tab6_gold_layout)

    # description
    self.tab6_description_layout = QtGui.QGroupBox("Description", self.tab6)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.tab6_description_layout.sizePolicy().hasHeightForWidth())
    self.tab6_description_layout.setSizePolicy(sizePolicy)
    self.tab6_description_layout.setObjectName(_fromUtf8("tab6_description_layout"))
    self.horizontalLayout_25 = QtGui.QHBoxLayout(self.tab6_description_layout)
    self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
    self.tab6_buy_layout = QtGui.QVBoxLayout()
    self.tab6_buy_layout.setObjectName(_fromUtf8("tab6_buy_layout"))
    self.tab6_buy_button = QtGui.QPushButton("Buy", self.tab6_description_layout)
    self.tab6_buy_button.setObjectName(_fromUtf8("tab6_buy_button"))
    self.tab6_buy_layout.addWidget(self.tab6_buy_button)
    self.tab6_add_button = QtGui.QPushButton("Add", self.tab6_description_layout)
    self.tab6_add_button.setObjectName(_fromUtf8("tab6_add_button"))
    self.tab6_buy_layout.addWidget(self.tab6_add_button)
    self.horizontalLayout_25.addLayout(self.tab6_buy_layout)
    self.tab6_description = QtGui.QTextBrowser(self.tab6_description_layout)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.tab6_description.sizePolicy().hasHeightForWidth())
    self.tab6_description.setSizePolicy(sizePolicy)
    self.tab6_description.setObjectName(_fromUtf8("tab6_description"))
    self.horizontalLayout_25.addWidget(self.tab6_description)
    self.tab6_sell_layout = QtGui.QVBoxLayout()
    self.tab6_sell_layout.setObjectName(_fromUtf8("tab6_sell_layout"))
    self.tab6_sell_button = QtGui.QPushButton("Sell", self.tab6_description_layout)
    self.tab6_sell_button.setObjectName(_fromUtf8("tab6_sell_button"))
    self.tab6_sell_layout.addWidget(self.tab6_sell_button)
    self.tab6_remove_button = QtGui.QPushButton("Remove", self.tab6_description_layout)
    self.tab6_remove_button.setObjectName(_fromUtf8("tab6_remove_button"))
    self.tab6_sell_layout.addWidget(self.tab6_remove_button)
    self.horizontalLayout_25.addLayout(self.tab6_sell_layout)
    self.verticalLayout_6.addWidget(self.tab6_description_layout)
    self.main_tab.addTab(self.tab6, "Equipment")

