from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

def setupSpell(self):
    # tab
    self.tab4 = QtGui.QWidget()
    self.tab4.setObjectName(_fromUtf8("tab4"))
    self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab4)
    self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
    # spell tab
    self.tab4_spell_tab = QtGui.QTabWidget(self.tab4)
    self.tab4_spell_tab.setObjectName(_fromUtf8("tab4_spell_tab"))
    self.tab4_tab0 = QtGui.QWidget()
    self.tab4_tab0.setObjectName(_fromUtf8("tab4_tab0"))
    self.verticalLayout_9 = QtGui.QVBoxLayout(self.tab4_tab0)
    self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))

    # cantrip tab
    self.tab4_tab0_list_layout = QtGui.QGroupBox("List", self.tab4_tab0)
    self.tab4_tab0_list_layout.setObjectName(_fromUtf8("tab4_tab0_list_layout"))
    self.horizontalLayout_36 = QtGui.QHBoxLayout(self.tab4_tab0_list_layout)
    self.horizontalLayout_36.setObjectName(_fromUtf8("horizontalLayout_36"))
    # list
    self.tab4_tab0_list_tree = QtGui.QTreeWidget(self.tab4_tab0_list_layout)
    self.tab4_tab0_list_tree.currentItemChanged.connect(self.updateCantripDescription)
    self.tab4_tab0_list_tree.setObjectName(_fromUtf8("tab4_tab0_list_tree"))
    self.tab4_tab0_list_tree.headerItem().setText(0, "Name")
    self.tab4_tab0_list_tree.headerItem().setText(1, "Casting time")
    self.tab4_tab0_list_tree.headerItem().setText(2, "Range")
    self.tab4_tab0_list_tree.headerItem().setText(3, "Components")
    self.tab4_tab0_list_tree.headerItem().setText(4, "Duration")
    self.tab4_tab0_list_tree.headerItem().setText(5, "School")

    self.horizontalLayout_36.addWidget(self.tab4_tab0_list_tree)
    self.verticalLayout_9.addWidget(self.tab4_tab0_list_layout)
    self.tab4_tab0_button_layout = QtGui.QHBoxLayout()
    self.tab4_tab0_button_layout.setContentsMargins(-1, 0, -1, -1)
    self.tab4_tab0_button_layout.setObjectName(_fromUtf8("tab4_tab0_button_layout"))
    self.tab4_tab0_class_label = QtGui.QLabel("Spell Class", self.tab4_tab0)
    self.tab4_tab0_button_layout.addWidget(self.tab4_tab0_class_label)
        
    self.tab4_tab0_class_combo = QtGui.QComboBox(self.tab4_tab0)
    self.tab4_tab0_class_combo.setObjectName(_fromUtf8("tab4_tab0_class_combo"))
    self.tab4_tab0_button_layout.addWidget(self.tab4_tab0_class_combo)
    self.tab4_tab0_class_combo.addItem("Any")
    for i in self.class_parser.getListClass():
        self.tab4_tab0_class_combo.addItem(i)
    self.tab4_tab0_class_combo.activated[str].connect(self.selectClassSpell)

    self.tab4_tab0_add_button = QtGui.QPushButton("Add", self.tab4_tab0)
    self.tab4_tab0_add_button.setObjectName(_fromUtf8("tab4_tab0_add_button"))
    self.tab4_tab0_add_button.clicked.connect(self.addCantrip)
    self.tab4_tab0_button_layout.addWidget(self.tab4_tab0_add_button)
    self.tab4_tab0_remove_button = QtGui.QPushButton("Remove", self.tab4_tab0)
    self.tab4_tab0_remove_button.setObjectName(_fromUtf8("tab4_tab0_remove_button"))
    self.tab4_tab0_remove_button.clicked.connect(self.removeCantrip)
    self.tab4_tab0_button_layout.addWidget(self.tab4_tab0_remove_button)
    self.verticalLayout_9.addLayout(self.tab4_tab0_button_layout)
    self.tab4_tab0_lower_layout = QtGui.QHBoxLayout()
    self.tab4_tab0_lower_layout.setObjectName(_fromUtf8("tab4_tab0_lower_layout"))
    # known
    self.tab4_tab0_know_layout = QtGui.QGroupBox("Known", self.tab4_tab0)
    self.tab4_tab0_know_layout.setObjectName(_fromUtf8("tab4_tab0_know_layout"))
    self.verticalLayout_11 = QtGui.QVBoxLayout(self.tab4_tab0_know_layout)
    self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
    self.tab4_tab0_known_tree = QtGui.QTreeWidget(self.tab4_tab0_know_layout)
    self.tab4_tab0_known_tree.setObjectName(_fromUtf8("tab4_tab0_known_tree"))
    self.tab4_tab0_known_tree.headerItem().setText(0, "Name")
    self.tab4_tab0_known_tree.headerItem().setText(1, "Casting time")
    self.tab4_tab0_known_tree.headerItem().setText(2, "Range")
    self.tab4_tab0_known_tree.headerItem().setText(3, "Components")
    self.tab4_tab0_known_tree.headerItem().setText(4, "Duration")
    self.tab4_tab0_known_tree.headerItem().setText(5, "School")
    self.tab4_tab0_known_tree.currentItemChanged.connect(self.updateCantripDescription)

    self.verticalLayout_11.addWidget(self.tab4_tab0_known_tree)
    self.tab4_tab0_lower_layout.addWidget(self.tab4_tab0_know_layout)
    self.tab4_tab0_description = QtGui.QTextBrowser(self.tab4_tab0)
    self.tab4_tab0_description.setObjectName(_fromUtf8("tab4_tab0_description"))
    self.tab4_tab0_lower_layout.addWidget(self.tab4_tab0_description)
    self.verticalLayout_9.addLayout(self.tab4_tab0_lower_layout)
    self.tab4_tab0_available_label = QtGui.QLabel("Cantrip known: 4/6", self.tab4_tab0)
    self.tab4_tab0_available_label.setAlignment(QtCore.Qt.AlignCenter)
    self.tab4_tab0_available_label.setObjectName(_fromUtf8("tab4_tab0_available_label"))
    self.verticalLayout_9.addWidget(self.tab4_tab0_available_label)
    self.tab4_spell_tab.addTab(self.tab4_tab0, "Cantrips")

    # Spells
    self.tab4_tab1 = QtGui.QWidget()
    self.tab4_tab1.setObjectName(_fromUtf8("tab4_tab1"))
    self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab4_tab1)
    self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
    # list
    self.tab4_tab1_list_layout = QtGui.QGroupBox("List", self.tab4_tab1)
    self.tab4_tab1_list_layout.setObjectName(_fromUtf8("tab4_tab1_list_layout"))
    self.horizontalLayout_7 = QtGui.QHBoxLayout(self.tab4_tab1_list_layout)
    self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
    self.tab4_tab1_list_tree = QtGui.QTreeWidget(self.tab4_tab1_list_layout)
    self.tab4_tab1_list_tree.setObjectName(_fromUtf8("tab4_tab1_list_tree"))
    self.tab4_tab1_list_tree.headerItem().setText(0, "Name")
    self.tab4_tab1_list_tree.headerItem().setText(1, "Casting Time")
    self.tab4_tab1_list_tree.headerItem().setText(2, "Range")
    self.tab4_tab1_list_tree.headerItem().setText(3, "Components")
    self.tab4_tab1_list_tree.headerItem().setText(4, "Duration")
    self.tab4_tab1_list_tree.headerItem().setText(5, "School")
    self.tab4_tab1_list_tree.currentItemChanged.connect(self.updateSpellDescription)

        
    __sortingEnabled = self.tab4_tab1_list_tree.isSortingEnabled()
    self.tab4_tab1_list_tree.setSortingEnabled(__sortingEnabled)
    self.tab4_tab1_list_tree.setSortingEnabled(False)
    self.horizontalLayout_7.addWidget(self.tab4_tab1_list_tree)
    self.verticalLayout_5.addWidget(self.tab4_tab1_list_layout)
    self.tab4_tab1_button_layout = QtGui.QHBoxLayout()
    self.tab4_tab1_button_layout.setContentsMargins(-1, 0, -1, -1)
    self.tab4_tab1_button_layout.setObjectName(_fromUtf8("tab4_tab1_button_layout"))
    self.tab4_tab1_class_label = QtGui.QLabel("Spell Class", self.tab4_tab1)
    self.tab4_tab1_button_layout.addWidget(self.tab4_tab1_class_label)
        
    self.tab4_tab1_class_combo = QtGui.QComboBox(self.tab4_tab1)
    self.tab4_tab1_class_combo.setObjectName(_fromUtf8("tab4_tab1_class_combo"))
    self.tab4_tab1_button_layout.addWidget(self.tab4_tab1_class_combo)
    self.tab4_tab1_class_combo.addItem("Any")
    for i in self.class_parser.getListClass():
        self.tab4_tab1_class_combo.addItem(i)
    self.tab4_tab1_class_combo.activated[str].connect(self.selectClassSpell)

    self.tab4_tab1_add_button = QtGui.QPushButton("Add", self.tab4_tab1)
    self.tab4_tab1_add_button.setObjectName(_fromUtf8("tab4_tab1_add_button"))
    self.tab4_tab1_add_button.clicked.connect(self.addSpell)
    self.tab4_tab1_button_layout.addWidget(self.tab4_tab1_add_button)
    self.tab4_tab1_remove_button = QtGui.QPushButton("Remove", self.tab4_tab1)
    self.tab4_tab1_remove_button.setObjectName(_fromUtf8("tab4_tab1_remove_button"))
    self.tab4_tab1_remove_button.clicked.connect(self.removeSpell)
    self.tab4_tab1_button_layout.addWidget(self.tab4_tab1_remove_button)
    self.verticalLayout_5.addLayout(self.tab4_tab1_button_layout)
    self.tab4_tab1_lower_layout = QtGui.QHBoxLayout()
    self.tab4_tab1_lower_layout.setObjectName(_fromUtf8("tab4_tab1_lower_layout"))
    # known
    self.tab4_tab1_known_layout = QtGui.QGroupBox("Known", self.tab4_tab1)
    self.tab4_tab1_known_layout.setObjectName(_fromUtf8("tab4_tab1_known_layout"))
    self.horizontalLayout_8 = QtGui.QHBoxLayout(self.tab4_tab1_known_layout)
    self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
    self.tab4_tab1_known_tree = QtGui.QTreeWidget(self.tab4_tab1_known_layout)
    self.tab4_tab1_known_tree.setObjectName(_fromUtf8("tab4_tab1_known_tree"))
    self.tab4_tab1_known_tree.headerItem().setText(0, _fromUtf8("Name"))
    self.horizontalLayout_8.addWidget(self.tab4_tab1_known_tree)
    self.tab4_tab1_lower_layout.addWidget(self.tab4_tab1_known_layout)
    self.tab4_tab1_known_tree.headerItem().setText(1, "Casting time")
    self.tab4_tab1_known_tree.headerItem().setText(2, "Range")
    self.tab4_tab1_known_tree.headerItem().setText(3, "Components")
    self.tab4_tab1_known_tree.headerItem().setText(4, "Duration")
    self.tab4_tab1_known_tree.headerItem().setText(4, "School")
    self.tab4_tab1_known_tree.currentItemChanged.connect(self.updateSpellDescription)
        
    self.tab4_tab1_description = QtGui.QTextBrowser(self.tab4_tab1)
    self.tab4_tab1_description.setObjectName(_fromUtf8("tab4_tab1_description"))
    self.tab4_tab1_lower_layout.addWidget(self.tab4_tab1_description)
    self.verticalLayout_5.addLayout(self.tab4_tab1_lower_layout)
    self.tab4_tab1_available_label = QtGui.QLabel("Spells known: 4/5", self.tab4_tab1)
    self.tab4_tab1_available_label.setAlignment(QtCore.Qt.AlignCenter)
    self.tab4_tab1_available_label.setObjectName(_fromUtf8("tab4_tab1_available_label"))
    self.verticalLayout_5.addWidget(self.tab4_tab1_available_label)
    self.tab4_spell_tab.addTab(self.tab4_tab1, "Spells")
    
    # Spell slots
    self.tab4_tab2 = QtGui.QWidget()
    self.tab4_tab2.setObjectName(_fromUtf8("tab4_tab2"))
    self.verticalLayout_12 = QtGui.QVBoxLayout(self.tab4_tab2)
    self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
    # button
    self.tab4_tab2_button_layout = QtGui.QHBoxLayout()
    self.tab4_tab2_button_layout.setObjectName(_fromUtf8("tab4_tab2_button_layout"))
    self.tab4_tab2_rest_button = QtGui.QPushButton("Long Rest", self.tab4_tab2)
    self.tab4_tab2_rest_button.setObjectName(_fromUtf8("tab4_tab2_rest_button"))
    self.tab4_tab2_button_layout.addWidget(self.tab4_tab2_rest_button)
    self.tab4_tab2_reset_button = QtGui.QPushButton("Reset Spell Choice", self.tab4_tab2)
    self.tab4_tab2_reset_button.setObjectName(_fromUtf8("tab4_tab2_reset_button"))
    self.tab4_tab2_button_layout.addWidget(self.tab4_tab2_reset_button)
    spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
    self.tab4_tab2_button_layout.addItem(spacerItem6)
    self.verticalLayout_12.addLayout(self.tab4_tab2_button_layout)
    # 1st level
    self.tab4_tab2_1_layout = QtGui.QGroupBox("1st Level", self.tab4_tab2)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.tab4_tab2_1_layout.sizePolicy().hasHeightForWidth())
    self.tab4_tab2_1_layout.setSizePolicy(sizePolicy)
    self.tab4_tab2_1_layout.setObjectName(_fromUtf8("tab4_tab2_1_layout"))
    self.gridLayout_3 = QtGui.QGridLayout(self.tab4_tab2_1_layout)
    self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
    self.tab4_tab2_1_used3 = QtGui.QRadioButton("Used", self.tab4_tab2_1_layout)
    self.tab4_tab2_1_used3.setObjectName(_fromUtf8("tab4_tab2_1_used3"))
    self.gridLayout_3.addWidget(self.tab4_tab2_1_used3, 1, 1, 1, 1)
    self.tab4_tab2_1_used1 = QtGui.QRadioButton("Used", self.tab4_tab2_1_layout)
    self.tab4_tab2_1_used1.setObjectName(_fromUtf8("tab4_tab2_1_used1"))
    self.gridLayout_3.addWidget(self.tab4_tab2_1_used1, 0, 1, 1, 1)
    self.tab4_tab2_1_used2 = QtGui.QRadioButton("Used", self.tab4_tab2_1_layout)
    self.tab4_tab2_1_used2.setObjectName(_fromUtf8("tab4_tab2_1_used2"))
    self.gridLayout_3.addWidget(self.tab4_tab2_1_used2, 0, 3, 1, 1)
    self.tab4_tab2_1_used4 = QtGui.QRadioButton("Used", self.tab4_tab2_1_layout)
    self.tab4_tab2_1_used4.setObjectName(_fromUtf8("tab4_tab2_1_used4"))
    self.gridLayout_3.addWidget(self.tab4_tab2_1_used4, 1, 3, 1, 1)
    self.tab4_tab2_1_slot1 = QtGui.QPushButton("Empty Spell Slot", self.tab4_tab2_1_layout)
    self.tab4_tab2_1_slot1.setObjectName(_fromUtf8("tab4_tab2_1_slot1"))
    self.gridLayout_3.addWidget(self.tab4_tab2_1_slot1, 0, 0, 1, 1)
    self.tab4_tab2_1_slot3 = QtGui.QPushButton("Empty Spell Slot", self.tab4_tab2_1_layout)
    self.tab4_tab2_1_slot3.setObjectName(_fromUtf8("tab4_tab2_1_slot3"))
    self.gridLayout_3.addWidget(self.tab4_tab2_1_slot3, 1, 0, 1, 1)
    self.tab4_tab2_1_slot2 = QtGui.QPushButton("Empty Spell Slot", self.tab4_tab2_1_layout)
    self.tab4_tab2_1_slot2.setObjectName(_fromUtf8("tab4_tab2_1_slot2"))
    self.gridLayout_3.addWidget(self.tab4_tab2_1_slot2, 0, 2, 1, 1)
    self.tab4_tab2_1_slot4 = QtGui.QPushButton("Empty Spell Slot", self.tab4_tab2_1_layout)
    self.tab4_tab2_1_slot4.setObjectName(_fromUtf8("tab4_tab2_1_slot4"))
    self.gridLayout_3.addWidget(self.tab4_tab2_1_slot4, 1, 2, 1, 1)
    self.verticalLayout_12.addWidget(self.tab4_tab2_1_layout)
    # 2nd level
    self.tab4_tab2_2_layout = QtGui.QGroupBox("2nd Level", self.tab4_tab2)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.tab4_tab2_2_layout.sizePolicy().hasHeightForWidth())
    self.tab4_tab2_2_layout.setSizePolicy(sizePolicy)
    self.tab4_tab2_2_layout.setObjectName(_fromUtf8("tab4_tab2_2_layout"))
    self.verticalLayout_12.addWidget(self.tab4_tab2_2_layout)
    # 3rd level
    self.tab4_tab2_3_layout = QtGui.QGroupBox("3rd Level", self.tab4_tab2)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.tab4_tab2_3_layout.sizePolicy().hasHeightForWidth())
    self.tab4_tab2_3_layout.setSizePolicy(sizePolicy)
    self.tab4_tab2_3_layout.setObjectName(_fromUtf8("tab4_tab2_3_layout"))
    self.verticalLayout_12.addWidget(self.tab4_tab2_3_layout)
    self.tab4_tab2_lower_layout = QtGui.QGridLayout()
    self.tab4_tab2_lower_layout.setObjectName(_fromUtf8("tab4_tab2_lower_layout"))
    # 4th level
    self.tab4_tab2_4_layout = QtGui.QGroupBox("4th Level", self.tab4_tab2)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.tab4_tab2_4_layout.sizePolicy().hasHeightForWidth())
    self.tab4_tab2_4_layout.setSizePolicy(sizePolicy)
    self.tab4_tab2_4_layout.setObjectName(_fromUtf8("tab4_tab2_4_layout"))
    self.tab4_tab2_lower_layout.addWidget(self.tab4_tab2_4_layout, 1, 0, 1, 1)
    # 5th level
    self.tab4_tab2_5_layout = QtGui.QGroupBox("5th Level", self.tab4_tab2)
    self.tab4_tab2_5_layout.setObjectName(_fromUtf8("tab4_tab2_5_layout"))
    self.tab4_tab2_lower_layout.addWidget(self.tab4_tab2_5_layout, 1, 1, 1, 1)
    # 6th level
    self.tab4_tab2_6_layout = QtGui.QGroupBox("6th Level", self.tab4_tab2)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.tab4_tab2_6_layout.sizePolicy().hasHeightForWidth())
    self.tab4_tab2_6_layout.setSizePolicy(sizePolicy)
    self.tab4_tab2_6_layout.setObjectName(_fromUtf8("tab4_tab2_6_layout"))
    # 7th level
    self.tab4_tab2_lower_layout.addWidget(self.tab4_tab2_6_layout, 2, 0, 1, 1)
    self.tab4_tab2_7_layout = QtGui.QGroupBox("7th Level", self.tab4_tab2)
    self.tab4_tab2_7_layout.setObjectName(_fromUtf8("tab4_tab2_7_layout"))
    self.tab4_tab2_lower_layout.addWidget(self.tab4_tab2_7_layout, 2, 1, 1, 1)
    # 8th level
    self.tab4_tab2_8_layout = QtGui.QGroupBox("8th Level", self.tab4_tab2)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.tab4_tab2_8_layout.sizePolicy().hasHeightForWidth())
    self.tab4_tab2_8_layout.setSizePolicy(sizePolicy)
    self.tab4_tab2_8_layout.setObjectName(_fromUtf8("tab4_tab2_8_layout"))
    self.tab4_tab2_lower_layout.addWidget(self.tab4_tab2_8_layout, 3, 0, 1, 1)
    # 9th level
    self.tab4_tab2_9_layout = QtGui.QGroupBox("9th Level", self.tab4_tab2)
    self.tab4_tab2_9_layout.setObjectName(_fromUtf8("tab4_tab2_9_layout"))
    self.tab4_tab2_lower_layout.addWidget(self.tab4_tab2_9_layout, 3, 1, 1, 1)
    self.verticalLayout_12.addLayout(self.tab4_tab2_lower_layout)
    self.tab4_spell_tab.addTab(self.tab4_tab2, "Spell Slots")

    # Trait
    self.tab4_tab3 = QtGui.QWidget()
    self.tab4_tab3.setObjectName(_fromUtf8("tab4_tab3"))
    self.horizontalLayout_40 = QtGui.QHBoxLayout(self.tab4_tab3)
    self.horizontalLayout_40.setObjectName(_fromUtf8("horizontalLayout_40"))
    self.tab4_tab3_tree = QtGui.QTreeWidget(self.tab4_tab3)
    self.tab4_tab3_tree.setObjectName(_fromUtf8("tab4_tab3_tree"))
    self.tab4_tab3_tree.headerItem().setText(0, "Name")
    self.tab4_tab3_tree.headerItem().setText(1, "Max uses")
    self.horizontalLayout_40.addWidget(self.tab4_tab3_tree)
    self.tab4_tab3_description = QtGui.QTextBrowser(self.tab4_tab3)
    self.tab4_tab3_description.setObjectName(_fromUtf8("tab4_tab3_description"))
    self.horizontalLayout_40.addWidget(self.tab4_tab3_description)
    self.tab4_spell_tab.addTab(self.tab4_tab3, "Trait")

    self.selectClassSpell('any')
    self.verticalLayout_3.addWidget(self.tab4_spell_tab)
    self.main_tab.addTab(self.tab4, "Spells/Traits")

