from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s
        
def setupStat(self):
    self.tab8 = QtGui.QWidget()
    self.tab8.setObjectName(_fromUtf8("tab8"))
    self.horizontalLayout_38 = QtGui.QHBoxLayout(self.tab8)
    self.horizontalLayout_38.setObjectName(_fromUtf8("horizontalLayout_38"))
    self.tab8_abilities_proficiencies_layout = QtGui.QVBoxLayout()
    self.tab8_abilities_proficiencies_layout.setObjectName(_fromUtf8("tab8_abilities_proficiencies_layout"))
        
    # abilities
    self.tab8_abilities_layout = QtGui.QGroupBox("Abilities", self.tab8)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.tab8_abilities_layout.sizePolicy().hasHeightForWidth())
    self.tab8_abilities_layout.setSizePolicy(sizePolicy)
    self.tab8_abilities_layout.setObjectName(_fromUtf8("tab8_abilities_layout"))
    self.gridLayout_5 = QtGui.QGridLayout(self.tab8_abilities_layout)
    self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
    self.tab8_abilities_up_layout = QtGui.QGridLayout()
    self.tab8_abilities_up_layout.setContentsMargins(-1, 0, -1, -1)
    self.tab8_abilities_up_layout.setObjectName(_fromUtf8("tab8_abilities_up_layout"))
    self.tab8_str_label = QtGui.QLabel("Strength", self.tab8_abilities_layout)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.tab8_str_label.sizePolicy().hasHeightForWidth())
    self.tab8_str_label.setSizePolicy(sizePolicy)
    self.tab8_str_label.setMinimumSize(QtCore.QSize(0, 20))
    self.tab8_str_label.setMaximumSize(QtCore.QSize(16777215, 10))
    self.tab8_str_label.setAlignment(QtCore.Qt.AlignCenter)
    self.tab8_str_label.setObjectName(_fromUtf8("tab8_str_label"))
    self.tab8_abilities_up_layout.addWidget(self.tab8_str_label, 0, 0, 1, 1)
    self.tab8_dex_label = QtGui.QLabel("Dexterity", self.tab8_abilities_layout)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.tab8_dex_label.sizePolicy().hasHeightForWidth())
    self.tab8_dex_label.setSizePolicy(sizePolicy)
    self.tab8_dex_label.setMinimumSize(QtCore.QSize(0, 20))
    self.tab8_dex_label.setMaximumSize(QtCore.QSize(16777215, 10))
    self.tab8_dex_label.setAlignment(QtCore.Qt.AlignCenter)
    self.tab8_dex_label.setObjectName(_fromUtf8("tab8_dex_label"))
    self.tab8_abilities_up_layout.addWidget(self.tab8_dex_label, 0, 1, 1, 1)
    self.tab8_con_label = QtGui.QLabel("Constitution", self.tab8_abilities_layout)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.tab8_con_label.sizePolicy().hasHeightForWidth())
    self.tab8_con_label.setSizePolicy(sizePolicy)
    self.tab8_con_label.setMinimumSize(QtCore.QSize(0, 20))
    self.tab8_con_label.setMaximumSize(QtCore.QSize(16777215, 10))
    self.tab8_con_label.setAlignment(QtCore.Qt.AlignCenter)
    self.tab8_con_label.setObjectName(_fromUtf8("tab8_con_label"))
    self.tab8_abilities_up_layout.addWidget(self.tab8_con_label, 0, 2, 1, 1)
    self.tab8_str_value = QtGui.QLabel("12 (+1)", self.tab8_abilities_layout)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.tab8_str_value.sizePolicy().hasHeightForWidth())
    self.tab8_str_value.setSizePolicy(sizePolicy)
    self.tab8_str_value.setMinimumSize(QtCore.QSize(0, 20))
    self.tab8_str_value.setMaximumSize(QtCore.QSize(16777215, 10))
    self.tab8_str_value.setAlignment(QtCore.Qt.AlignCenter)
    self.tab8_str_value.setObjectName(_fromUtf8("tab8_str_value"))
    self.tab8_abilities_up_layout.addWidget(self.tab8_str_value, 1, 0, 1, 1)
    self.tab8_dex_value = QtGui.QLabel("11 (+0)", self.tab8_abilities_layout)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.tab8_dex_value.sizePolicy().hasHeightForWidth())
    self.tab8_dex_value.setSizePolicy(sizePolicy)
    self.tab8_dex_value.setMinimumSize(QtCore.QSize(0, 20))
    self.tab8_dex_value.setMaximumSize(QtCore.QSize(16777215, 10))
    self.tab8_dex_value.setAlignment(QtCore.Qt.AlignCenter)
    self.tab8_dex_value.setObjectName(_fromUtf8("tab8_dex_value"))
    self.tab8_abilities_up_layout.addWidget(self.tab8_dex_value, 1, 1, 1, 1)
    self.tab8_con_value = QtGui.QLabel("9 (-1)", self.tab8_abilities_layout)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.tab8_con_value.sizePolicy().hasHeightForWidth())
    self.tab8_con_value.setSizePolicy(sizePolicy)
    self.tab8_con_value.setMinimumSize(QtCore.QSize(0, 20))
    self.tab8_con_value.setMaximumSize(QtCore.QSize(16777215, 10))
    self.tab8_con_value.setAlignment(QtCore.Qt.AlignCenter)
    self.tab8_con_value.setObjectName(_fromUtf8("tab8_con_value"))
    self.tab8_abilities_up_layout.addWidget(self.tab8_con_value, 1, 2, 1, 1)
    self.gridLayout_5.addLayout(self.tab8_abilities_up_layout, 0, 0, 1, 1)
    self.tab8_abilities_sub_layout = QtGui.QGridLayout()
    self.tab8_abilities_sub_layout.setContentsMargins(-1, 10, -1, 10)
    self.tab8_abilities_sub_layout.setObjectName(_fromUtf8("tab8_abilities_sub_layout"))
    self.tab8_wis_label = QtGui.QLabel("Wisdom", self.tab8_abilities_layout)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.tab8_wis_label.sizePolicy().hasHeightForWidth())
    self.tab8_wis_label.setSizePolicy(sizePolicy)
    self.tab8_wis_label.setMinimumSize(QtCore.QSize(0, 20))
    self.tab8_wis_label.setMaximumSize(QtCore.QSize(16777215, 10))
    self.tab8_wis_label.setAlignment(QtCore.Qt.AlignCenter)
    self.tab8_wis_label.setObjectName(_fromUtf8("tab8_wis_label"))
    self.tab8_abilities_sub_layout.addWidget(self.tab8_wis_label, 0, 1, 1, 1)
    self.tab8_cha_label = QtGui.QLabel("Charisma", self.tab8_abilities_layout)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.tab8_cha_label.sizePolicy().hasHeightForWidth())
    self.tab8_cha_label.setSizePolicy(sizePolicy)
    self.tab8_cha_label.setMinimumSize(QtCore.QSize(0, 20))
    self.tab8_cha_label.setMaximumSize(QtCore.QSize(16777215, 10))
    self.tab8_cha_label.setAlignment(QtCore.Qt.AlignCenter)
    self.tab8_cha_label.setObjectName(_fromUtf8("tab8_cha_label"))
    self.tab8_abilities_sub_layout.addWidget(self.tab8_cha_label, 0, 2, 1, 1)
    self.tab8_int_label = QtGui.QLabel("Intelligence", self.tab8_abilities_layout)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.tab8_int_label.sizePolicy().hasHeightForWidth())
    self.tab8_int_label.setSizePolicy(sizePolicy)
    self.tab8_int_label.setMinimumSize(QtCore.QSize(0, 20))
    self.tab8_int_label.setMaximumSize(QtCore.QSize(16777215, 10))
    self.tab8_int_label.setAlignment(QtCore.Qt.AlignCenter)
    self.tab8_int_label.setObjectName(_fromUtf8("tab8_int_label"))
    self.tab8_abilities_sub_layout.addWidget(self.tab8_int_label, 0, 0, 1, 1)
    self.tab8_int_value = QtGui.QLabel("16 (+3)", self.tab8_abilities_layout)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.tab8_int_value.sizePolicy().hasHeightForWidth())
    self.tab8_int_value.setSizePolicy(sizePolicy)
    self.tab8_int_value.setMinimumSize(QtCore.QSize(0, 20))
    self.tab8_int_value.setMaximumSize(QtCore.QSize(16777215, 10))
    self.tab8_int_value.setAlignment(QtCore.Qt.AlignCenter)
    self.tab8_int_value.setObjectName(_fromUtf8("tab8_int_value"))
    self.tab8_abilities_sub_layout.addWidget(self.tab8_int_value, 1, 0, 1, 1)
    self.tab8_wis_value = QtGui.QLabel("10 (+0)", self.tab8_abilities_layout)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.tab8_wis_value.sizePolicy().hasHeightForWidth())
    self.tab8_wis_value.setSizePolicy(sizePolicy)
    self.tab8_wis_value.setMinimumSize(QtCore.QSize(0, 20))
    self.tab8_wis_value.setMaximumSize(QtCore.QSize(16777215, 10))
    self.tab8_wis_value.setAlignment(QtCore.Qt.AlignCenter)
    self.tab8_wis_value.setObjectName(_fromUtf8("tab8_wis_value"))
    self.tab8_abilities_sub_layout.addWidget(self.tab8_wis_value, 1, 1, 1, 1)
    self.tab8_cha_value = QtGui.QLabel("10 (+0)", self.tab8_abilities_layout)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.tab8_cha_value.sizePolicy().hasHeightForWidth())
    self.tab8_cha_value.setSizePolicy(sizePolicy)
    self.tab8_cha_value.setMinimumSize(QtCore.QSize(0, 20))
    self.tab8_cha_value.setMaximumSize(QtCore.QSize(16777215, 10))
    self.tab8_cha_value.setAlignment(QtCore.Qt.AlignCenter)
    self.tab8_cha_value.setObjectName(_fromUtf8("tab8_cha_value"))
    self.tab8_abilities_sub_layout.addWidget(self.tab8_cha_value, 1, 2, 1, 1)
    self.gridLayout_5.addLayout(self.tab8_abilities_sub_layout, 1, 0, 1, 1)

    # proficiencies
    self.tab8_abilities_proficiencies_layout.addWidget(self.tab8_abilities_layout)
    self.tab8_proficiencies_layout = QtGui.QGroupBox("Proficiencies", self.tab8)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.tab8_proficiencies_layout.sizePolicy().hasHeightForWidth())
    self.tab8_proficiencies_layout.setSizePolicy(sizePolicy)
    self.tab8_proficiencies_layout.setObjectName(_fromUtf8("tab8_proficiencies_layout"))
    self.gridLayout_11 = QtGui.QGridLayout(self.tab8_proficiencies_layout)
    self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
    self.tab8_saving_layout = QtGui.QGroupBox("Saving Throws", self.tab8_proficiencies_layout)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.tab8_saving_layout.sizePolicy().hasHeightForWidth())
    self.tab8_saving_layout.setSizePolicy(sizePolicy)
    self.tab8_saving_layout.setObjectName(_fromUtf8("tab8_saving_layout"))
    self.gridLayout_12 = QtGui.QGridLayout(self.tab8_saving_layout)
    self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
    self.tab8_saving_1_label = QtGui.QLabel("Dexterity", self.tab8_saving_layout)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.tab8_saving_1_label.sizePolicy().hasHeightForWidth())
    self.tab8_saving_1_label.setSizePolicy(sizePolicy)
    self.tab8_saving_1_label.setMinimumSize(QtCore.QSize(20, 0))
    self.tab8_saving_1_label.setAlignment(QtCore.Qt.AlignCenter)
    self.tab8_saving_1_label.setObjectName(_fromUtf8("tab8_saving_1_label"))
    self.gridLayout_12.addWidget(self.tab8_saving_1_label, 0, 0, 1, 1)
    self.tab8_saving_2_label = QtGui.QLabel("Intelligence", self.tab8_saving_layout)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.tab8_saving_2_label.sizePolicy().hasHeightForWidth())
    self.tab8_saving_2_label.setSizePolicy(sizePolicy)
    self.tab8_saving_2_label.setMinimumSize(QtCore.QSize(20, 0))
    self.tab8_saving_2_label.setAlignment(QtCore.Qt.AlignCenter)
    self.tab8_saving_2_label.setObjectName(_fromUtf8("tab8_saving_2_label"))
    self.gridLayout_12.addWidget(self.tab8_saving_2_label, 0, 1, 1, 1)
    self.gridLayout_11.addWidget(self.tab8_saving_layout, 0, 0, 1, 1)
    # skills
    self.tab8_skill_layout = QtGui.QGroupBox("Skills", self.tab8_proficiencies_layout)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.tab8_skill_layout.sizePolicy().hasHeightForWidth())
    self.tab8_skill_layout.setSizePolicy(sizePolicy)
    self.tab8_skill_layout.setObjectName(_fromUtf8("tab8_skill_layout"))
    self.gridLayout_13 = QtGui.QGridLayout(self.tab8_skill_layout)
    self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
    self.tab8_skill3 = QtGui.QLabel("Insight (Wisdom +2)", self.tab8_skill_layout)
    self.tab8_skill3.setObjectName(_fromUtf8("tab8_skill3"))
    self.gridLayout_13.addWidget(self.tab8_skill3, 1, 1, 1, 1)
    self.tab8_skill2 = QtGui.QLabel("Religion (Wisdom +2)", self.tab8_skill_layout)
    self.tab8_skill2.setObjectName(_fromUtf8("tab8_skill2"))
    self.gridLayout_13.addWidget(self.tab8_skill2, 1, 0, 1, 1)
    self.tab8_skill4 = QtGui.QLabel("Club (Strength +2)", self.tab8_skill_layout)
    self.tab8_skill4.setObjectName(_fromUtf8("tab8_skill4"))
    self.gridLayout_13.addWidget(self.tab8_skill4, 2, 0, 1, 1)
    self.tab8_skill5 = QtGui.QLabel("Survival (Wisdom +2)", self.tab8_skill_layout)
    self.tab8_skill5.setObjectName(_fromUtf8("tab8_skill5"))
    self.gridLayout_13.addWidget(self.tab8_skill5, 2, 1, 1, 1)
    self.tab8_skill6 = QtGui.QLabel("Ligth Armor", self.tab8_skill_layout)
    self.tab8_skill6.setObjectName(_fromUtf8("tab8_skill6"))
    self.gridLayout_13.addWidget(self.tab8_skill6, 3, 0, 1, 1)
    self.tab8_skill7 = QtGui.QLabel("Perception (Wisdom +2)", self.tab8_skill_layout)
    self.tab8_skill7.setObjectName(_fromUtf8("tab8_skill7"))
    self.gridLayout_13.addWidget(self.tab8_skill7, 3, 1, 1, 1)
    self.tab8_skill1 = QtGui.QLabel("Shortsword (Dexterity +2)", self.tab8_skill_layout)
    self.tab8_skill1.setObjectName(_fromUtf8("tab8_skill1"))
    self.gridLayout_13.addWidget(self.tab8_skill1, 0, 1, 1, 1)
    self.tab8_passive_perc = QtGui.QLabel("Passive Perception (12)", self.tab8_skill_layout)
    self.tab8_passive_perc.setObjectName(_fromUtf8("tab8_passive_perc"))
    self.gridLayout_13.addWidget(self.tab8_passive_perc, 0, 0, 1, 1)
    self.gridLayout_11.addWidget(self.tab8_skill_layout, 1, 0, 1, 1)
    self.tab8_abilities_proficiencies_layout.addWidget(self.tab8_proficiencies_layout)
    self.horizontalLayout_38.addLayout(self.tab8_abilities_proficiencies_layout)

    # right part
    self.tab8_right_layout = QtGui.QGroupBox(self.tab8)
    self.tab8_right_layout.setTitle(_fromUtf8(""))
    self.tab8_right_layout.setObjectName(_fromUtf8("tab8_right_layout"))
    self.verticalLayout_16 = QtGui.QVBoxLayout(self.tab8_right_layout)
    self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
    self.tab8_hit_layout = QtGui.QGridLayout()
    self.tab8_hit_layout.setObjectName(_fromUtf8("tab8_hit_layout"))
    # 1st line
    self.tab8_ac_label = QtGui.QLabel("Armor Class", self.tab8_right_layout)
    self.tab8_ac_label.setAlignment(QtCore.Qt.AlignCenter)
    self.tab8_ac_label.setObjectName(_fromUtf8("tab8_ac_label"))
    self.tab8_hit_layout.addWidget(self.tab8_ac_label, 0, 2, 1, 1)
    self.tab8_max_hit_points_label = QtGui.QLabel("Max Hit Points", self.tab8_right_layout)
    self.tab8_max_hit_points_label.setObjectName(_fromUtf8("tab8_max_hit_points_label"))
    self.tab8_max_hit_points_label.setAlignment(QtCore.Qt.AlignCenter)
    self.tab8_hit_layout.addWidget(self.tab8_max_hit_points_label, 0, 1, 1, 1)
    self.tab8_hit_points_value = QtGui.QLabel("10", self.tab8_right_layout)
    self.tab8_hit_points_value.setObjectName(_fromUtf8("tab8_hit_points_value"))
    self.tab8_hit_points_value.setAlignment(QtCore.Qt.AlignCenter)
    self.tab8_hit_layout.addWidget(self.tab8_hit_points_value, 1, 0, 1, 1)
    self.tab8_max_hit_points_value = QtGui.QLabel("12", self.tab8_right_layout)
    self.tab8_max_hit_points_value.setObjectName(_fromUtf8("tab8_max_hit_points_value"))
    self.tab8_max_hit_points_value.setAlignment(QtCore.Qt.AlignCenter)
    self.tab8_hit_layout.addWidget(self.tab8_max_hit_points_value, 1, 1, 1, 1)
    self.tab8_ac_value = QtGui.QLabel("+2", self.tab8_right_layout)
    self.tab8_ac_value.setObjectName(_fromUtf8("tab8_ac_value"))
    self.tab8_ac_value.setAlignment(QtCore.Qt.AlignCenter)
    self.tab8_hit_layout.addWidget(self.tab8_ac_value, 1, 2, 1, 1)
    self.tab8_hit_points_label = QtGui.QLabel("Hit Points", self.tab8_right_layout)
    self.tab8_hit_points_label.setObjectName(_fromUtf8("tab8_hit_points_label"))
    self.tab8_hit_points_label.setAlignment(QtCore.Qt.AlignCenter)
    # 2nd line
    self.tab8_hit_layout.addWidget(self.tab8_hit_points_label, 0, 0, 1, 1)
    self.tab8_hit_dice_label = QtGui.QLabel("Hit Dice", self.tab8_right_layout)
    self.tab8_hit_dice_label.setObjectName(_fromUtf8("tab8_hit_dice_label"))
    self.tab8_hit_dice_label.setAlignment(QtCore.Qt.AlignCenter)
    self.tab8_hit_layout.addWidget(self.tab8_hit_dice_label, 2, 0, 1, 1)
    self.tab8_max_hit_dice_label = QtGui.QLabel("Max Hit Dice", self.tab8_right_layout)
    self.tab8_max_hit_dice_label.setObjectName(_fromUtf8("tab8_max_hit_dice_label"))
    self.tab8_max_hit_dice_label.setAlignment(QtCore.Qt.AlignCenter)
    self.tab8_hit_layout.addWidget(self.tab8_max_hit_dice_label, 2, 1, 1, 1)
    self.tab8_max_hit_dice_value = QtGui.QLabel("1d4", self.tab8_right_layout)
    self.tab8_max_hit_dice_value.setObjectName(_fromUtf8("tab8_max_hit_dice_value"))
    self.tab8_max_hit_dice_value.setAlignment(QtCore.Qt.AlignCenter)
    self.tab8_hit_layout.addWidget(self.tab8_max_hit_dice_value, 3, 1, 1, 1)
    self.tab8_speed_label = QtGui.QLabel("Speed", self.tab8_right_layout)
    self.tab8_speed_label.setObjectName(_fromUtf8("tab8_speed_label"))
    self.tab8_speed_label.setAlignment(QtCore.Qt.AlignCenter)
    self.tab8_hit_layout.addWidget(self.tab8_speed_label, 2, 2, 1, 1)
    self.tab8_hit_dice_value = QtGui.QLabel("0d4", self.tab8_right_layout)
    self.tab8_hit_dice_value.setObjectName(_fromUtf8("tab8_hit_dice_value"))
    self.tab8_hit_dice_value.setAlignment(QtCore.Qt.AlignCenter)
    self.tab8_hit_layout.addWidget(self.tab8_hit_dice_value, 3, 0, 1, 1)
    self.tab8_speed_value = QtGui.QLabel("30", self.tab8_right_layout)
    self.tab8_speed_value.setObjectName(_fromUtf8("tab8_speed_value"))
    self.tab8_speed_value.setAlignment(QtCore.Qt.AlignCenter)
    self.tab8_hit_layout.addWidget(self.tab8_speed_value, 3, 2, 1, 1)
    self.verticalLayout_16.addLayout(self.tab8_hit_layout)

    # features
    self.tab8_features_layout = QtGui.QGroupBox("Features", self.tab8_right_layout)
    self.tab8_features_layout.setObjectName(_fromUtf8("tab8_features_layout"))
    self.verticalLayout_28 = QtGui.QVBoxLayout(self.tab8_features_layout)
    self.verticalLayout_28.setObjectName(_fromUtf8("verticalLayout_28"))
    self.tab8_features_tree = QtGui.QTreeWidget(self.tab8_features_layout)
    self.tab8_features_tree.setObjectName(_fromUtf8("tab8_features_tree"))
    item_0 = QtGui.QTreeWidgetItem(self.tab8_features_tree)
    self.tab8_features_tree.headerItem().setText(0, "Name")
    self.tab8_features_tree.headerItem().setText(1, "Max uses")
    __sortingEnabled = self.tab8_features_tree.isSortingEnabled()
    self.tab8_features_tree.setSortingEnabled(False)
    self.tab8_features_tree.topLevelItem(0).setText(0, "Actor")
    self.tab8_features_tree.topLevelItem(0).setText(1, "Unlimited")
    self.tab8_features_tree.setSortingEnabled(__sortingEnabled)
    self.verticalLayout_28.addWidget(self.tab8_features_tree)
    self.verticalLayout_16.addWidget(self.tab8_features_layout)
    # spell
    self.tab8_spell_layout = QtGui.QGroupBox("Spells", self.tab8_right_layout)
    self.tab8_spell_layout.setObjectName(_fromUtf8("tab8_spell_layout"))
    self.horizontalLayout_41 = QtGui.QHBoxLayout(self.tab8_spell_layout)
    self.horizontalLayout_41.setObjectName(_fromUtf8("horizontalLayout_41"))
    self.tab8_spell_tree = QtGui.QTreeWidget(self.tab8_spell_layout)
    self.tab8_spell_tree.setObjectName(_fromUtf8("tab8_spell_tree"))
    item_0 = QtGui.QTreeWidgetItem(self.tab8_spell_tree)
    item_1 = QtGui.QTreeWidgetItem(item_0)
    self.tab8_spell_tree.headerItem().setText(0, "Name")
    self.tab8_spell_tree.headerItem().setText(1, "Type")
    self.tab8_spell_tree.headerItem().setText(2, "Casting time")
    self.tab8_spell_tree.headerItem().setText(3, "Range")
    self.tab8_spell_tree.headerItem().setText(4, "Components")
    self.tab8_spell_tree.headerItem().setText(5, "Duration")
    __sortingEnabled = self.tab8_spell_tree.isSortingEnabled()
    self.tab8_spell_tree.setSortingEnabled(False)
    self.tab8_spell_tree.topLevelItem(0).setText(0, "1st Level")
    self.tab8_spell_tree.topLevelItem(0).child(0).setText(0, "Animal Friendship")
    self.tab8_spell_tree.topLevelItem(0).child(0).setText(1, "Enchantment")
    self.tab8_spell_tree.topLevelItem(0).child(0).setText(2, "1 action")
    self.tab8_spell_tree.topLevelItem(0).child(0).setText(3, "30")
    self.tab8_spell_tree.topLevelItem(0).child(0).setText(4, "V, S, M (a morsel of food)")
    self.tab8_spell_tree.topLevelItem(0).child(0).setText(5, "24h")
    self.tab8_spell_tree.setSortingEnabled(__sortingEnabled)
    self.horizontalLayout_41.addWidget(self.tab8_spell_tree)
    self.verticalLayout_16.addWidget(self.tab8_spell_layout)
    self.horizontalLayout_38.addWidget(self.tab8_right_layout)
    self.main_tab.addTab(self.tab8, "Stats")
    
