from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

def setupBackground(self):
    self.page3 = QtGui.QWizardPage()
    self.page3.setObjectName(_fromUtf8("page3"))
    self.verticalLayout_10 = QtGui.QVBoxLayout(self.page3)
    self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
    # background
    self.page3_background_layout = QtGui.QGroupBox("Background", self.page3)
    self.page3_background_layout.setObjectName(_fromUtf8("page3_background_layout"))
    self.horizontalLayout_16 = QtGui.QHBoxLayout(self.page3_background_layout)
    self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
    self.page3_background_choice_layout = QtGui.QVBoxLayout()
    self.page3_background_choice_layout.setObjectName(_fromUtf8("page3_background_choice_layout"))
    self.page3_full_random_button = QtGui.QPushButton("Full Random", self.page3_background_layout)
    self.page3_full_random_button.clicked.connect(self.fullRandomBackground)
    self.page3_full_random_button.setObjectName(_fromUtf8("page3_full_random_button"))
    self.page3_background_choice_layout.addWidget(self.page3_full_random_button)
    self.page3_background_combo = QtGui.QComboBox(self.page3_background_layout)
    self.page3_background_combo.setObjectName(_fromUtf8("page3_background_combo"))
    for i in self.background_parser.getListBackground():
        self.page3_background_combo.addItem(i)

    self.page3_background_choice_layout.addWidget(self.page3_background_combo)
    self.page3_random_personality_button = QtGui.QPushButton("Random Personality", self.page3_background_layout)
    self.page3_random_personality_button.clicked.connect(self.randomPersonality)

    self.page3_random_personality_button.setObjectName(_fromUtf8("page3_random_personality_button"))
    self.page3_background_choice_layout.addWidget(self.page3_random_personality_button)
    self.horizontalLayout_16.addLayout(self.page3_background_choice_layout)
    self.page3_background_description = QtGui.QTextBrowser(self.page3_background_layout)
    self.page3_background_description.setObjectName(_fromUtf8("page3_background_description"))
    self.page3_background_combo.activated[str].connect(self.changeBackground)
    self.horizontalLayout_16.addWidget(self.page3_background_description)
    self.verticalLayout_10.addWidget(self.page3_background_layout)
    self.page3_lower_layout = QtGui.QVBoxLayout()
    self.page3_lower_layout.setObjectName(_fromUtf8("page3_lower_layout"))
    # choice
    self.page3_choice_layout = QtGui.QGroupBox("Choices", self.page3)
    self.page3_choice_layout.setObjectName(_fromUtf8("page3_choice_layout"))
    self.horizontalLayout_33 = QtGui.QHBoxLayout(self.page3_choice_layout)
    #
    self.page3_choice_list = []
    self.page3_lower_layout.addWidget(self.page3_choice_layout)
    # personality
    self.page3_personality_layout = QtGui.QGroupBox("Personality", self.page3)
    self.page3_personality_layout.setObjectName(_fromUtf8("page3_personality_layout"))
    self.horizontalLayout_12 = QtGui.QHBoxLayout(self.page3_personality_layout)
    self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
    self.page3_personality_choice_layout = QtGui.QVBoxLayout()
    self.page3_personality_choice_layout.setObjectName(_fromUtf8("page3_personality_choice_layout"))
    self.page3_personality_spinbox_1 = QtGui.QSpinBox(self.page3_personality_layout)
    self.page3_personality_spinbox_1.setMinimum(1)
    self.page3_personality_spinbox_1.valueChanged.connect(self.changePersonalityDescription)
    self.page3_personality_spinbox_1.setObjectName(_fromUtf8("page3_personality_spinbox_1"))
    self.page3_personality_choice_layout.addWidget(self.page3_personality_spinbox_1)
    self.page3_personality_spinbox_2 = QtGui.QSpinBox(self.page3_personality_layout)
    self.page3_personality_spinbox_2.setMinimum(1)
    self.page3_personality_spinbox_2.valueChanged.connect(self.changePersonalityDescription)
    self.page3_personality_spinbox_2.setObjectName(_fromUtf8("page3_personality_spinbox_2"))
    self.page3_personality_choice_layout.addWidget(self.page3_personality_spinbox_2)
    self.horizontalLayout_12.addLayout(self.page3_personality_choice_layout)
    self.page3_personality_description = QtGui.QTextBrowser(self.page3_personality_layout)
    self.page3_personality_description.setObjectName(_fromUtf8("page3_personality_description"))
    self.horizontalLayout_12.addWidget(self.page3_personality_description)
    self.page3_lower_layout.addWidget(self.page3_personality_layout)
    # ideal
    self.page3_ideal_layout = QtGui.QGroupBox("Ideal", self.page3)
    self.page3_ideal_layout.setObjectName(_fromUtf8("page3_ideal_layout"))
    self.horizontalLayout_13 = QtGui.QHBoxLayout(self.page3_ideal_layout)
    self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
    self.page3_ideal_choice_layout = QtGui.QVBoxLayout()
    self.page3_ideal_choice_layout.setContentsMargins(0, -1, -1, -1)
    self.page3_ideal_choice_layout.setObjectName(_fromUtf8("page3_ideal_choice_layout"))
    self.page3_ideal_combo = QtGui.QComboBox(self.page3_ideal_layout)
    self.page3_ideal_combo.activated[str].connect(self.changeIdealDescription)
    self.page3_ideal_combo.setObjectName(_fromUtf8("page3_ideal_combo"))        
    self.page3_ideal_choice_layout.addWidget(self.page3_ideal_combo)
    self.page3_alignment_combo = QtGui.QComboBox(self.page3_ideal_layout)
    self.page3_alignment_combo.setMinimumSize(QtCore.QSize(120, 0))
    self.page3_alignment_combo.setObjectName(_fromUtf8("page3_alignment_combo"))
    # alignment
    self.page3_alignment_combo.addItem("Lawful Good")
    self.page3_alignment_combo.addItem("Neutral Good")
    self.page3_alignment_combo.addItem("Chaotic Good")
    self.page3_alignment_combo.addItem("Lawful Neutral")
    self.page3_alignment_combo.addItem("True Neutral")
    self.page3_alignment_combo.addItem("Chaotic Neutral")
    self.page3_alignment_combo.addItem("Lawful Evil")
    self.page3_alignment_combo.addItem("Neutral Evil")
    self.page3_alignment_combo.addItem("Chaotic Evil")
    self.page3_alignment_combo.activated[str].connect(self.character.background.setAlignment)
    self.page3_ideal_choice_layout.addWidget(self.page3_alignment_combo)
    self.horizontalLayout_13.addLayout(self.page3_ideal_choice_layout)
    self.page3_ideal_description = QtGui.QTextBrowser(self.page3_ideal_layout)
    self.page3_ideal_description.setObjectName(_fromUtf8("page3_ideal_description"))
    self.horizontalLayout_13.addWidget(self.page3_ideal_description)
    self.page3_lower_layout.addWidget(self.page3_ideal_layout)
    # bond
    self.page3_bond_layout = QtGui.QGroupBox("Bond", self.page3)
    self.page3_bond_layout.setObjectName(_fromUtf8("page3_bond_layout"))
    self.horizontalLayout_15 = QtGui.QHBoxLayout(self.page3_bond_layout)
    self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
    self.page3_bond_spinbox = QtGui.QSpinBox(self.page3_bond_layout)
    self.page3_bond_spinbox.setMinimum(1)
    self.page3_bond_spinbox.valueChanged.connect(self.changeBondDescription)
    self.page3_bond_spinbox.setObjectName(_fromUtf8("page3_bond_spinbox"))
    self.horizontalLayout_15.addWidget(self.page3_bond_spinbox)
    self.page3_bond_description = QtGui.QTextBrowser(self.page3_bond_layout)
    self.page3_bond_description.setObjectName(_fromUtf8("page3_bond_description"))
    self.horizontalLayout_15.addWidget(self.page3_bond_description)
    self.page3_lower_layout.addWidget(self.page3_bond_layout)
    # flaw
    self.page3_flaw_layout = QtGui.QGroupBox("Flaw", self.page3)
    self.page3_flaw_layout.setObjectName(_fromUtf8("page3_flaw_layout"))
    self.horizontalLayout_14 = QtGui.QHBoxLayout(self.page3_flaw_layout)
    self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
    self.page3_flaw_spinbox = QtGui.QSpinBox(self.page3_flaw_layout)
    self.page3_flaw_spinbox.setMinimum(1)
    self.page3_flaw_spinbox.valueChanged.connect(self.changeFlawDescription)
    self.page3_flaw_spinbox.setObjectName(_fromUtf8("page3_flaw_spinbox"))
    self.horizontalLayout_14.addWidget(self.page3_flaw_spinbox)
    self.page3_flaw_description = QtGui.QTextBrowser(self.page3_flaw_layout)
    self.page3_flaw_description.setObjectName(_fromUtf8("page3_flaw_description"))
    self.horizontalLayout_14.addWidget(self.page3_flaw_description)
    self.page3_lower_layout.addWidget(self.page3_flaw_layout)
    self.verticalLayout_10.addLayout(self.page3_lower_layout)

    self.fullRandomBackground()
    return self.page3

