from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

def setupDescription(self):
    # create tab
    self.tab1 = QtGui.QWidget()
    self.tab1.setObjectName(_fromUtf8("tab1"))
    self.horizontalLayout_19 = QtGui.QHBoxLayout(self.tab1)
    self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))

    # create left side
    self.tab1_character_layout = QtGui.QGroupBox("Character", self.tab1)
    self.tab1_character_layout.setObjectName(_fromUtf8("tab1_character_layout"))
    self.verticalLayout_22 = QtGui.QVBoxLayout(self.tab1_character_layout)
    self.verticalLayout_22.setObjectName(_fromUtf8("verticalLayout_22"))
    
    # create character's form
    self.tab1_character_form = QtGui.QFormLayout()
    self.tab1_character_form.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
    self.tab1_character_form.setObjectName(_fromUtf8("tab1_character_form"))
    self.tab1_characterNameLabel = QtGui.QLabel("Character Name", self.tab1_character_layout)
    self.tab1_characterNameLabel.setObjectName(_fromUtf8("tab1_characterNameLabel"))
    self.tab1_character_form.setWidget(0, QtGui.QFormLayout.LabelRole, self.tab1_characterNameLabel)
    self.tab1_characterNameLineEdit = QtGui.QLineEdit(self.tab1_character_layout)
    self.tab1_characterNameLineEdit.textChanged.connect(self.character.setName)
    self.tab1_characterNameLineEdit.setObjectName(_fromUtf8("tab1_characterNameLineEdit"))
    self.tab1_character_form.setWidget(0, QtGui.QFormLayout.FieldRole, self.tab1_characterNameLineEdit)
    self.tab1_playerNameLabel = QtGui.QLabel("Player Name", self.tab1_character_layout)
    self.tab1_playerNameLabel.setObjectName(_fromUtf8("tab1_playerNameLabel"))
    self.tab1_character_form.setWidget(1, QtGui.QFormLayout.LabelRole, self.tab1_playerNameLabel)
    self.tab1_playerNameLineEdit = QtGui.QLineEdit(self.tab1_character_layout)
    self.tab1_playerNameLineEdit.textChanged.connect(self.character.setPlayer)
    self.tab1_playerNameLineEdit.setObjectName(_fromUtf8("tab1_playerNameLineEdit"))
    self.tab1_character_form.setWidget(1, QtGui.QFormLayout.FieldRole, self.tab1_playerNameLineEdit)
    self.tab1_campaignLabel = QtGui.QLabel("Campaign", self.tab1_character_layout)
    self.tab1_campaignLabel.setObjectName(_fromUtf8("tab1_campaignLabel"))
    self.tab1_character_form.setWidget(2, QtGui.QFormLayout.LabelRole, self.tab1_campaignLabel)
    self.tab1_campaignComboBox = QtGui.QComboBox(self.tab1_character_layout)
    self.tab1_campaignComboBox.activated[str].connect(self.character.setCampaign)
    self.tab1_campaignComboBox.setEditable(True)
    self.tab1_campaignComboBox.setObjectName(_fromUtf8("tab1_campaignComboBox"))
    self.tab1_character_form.setWidget(2, QtGui.QFormLayout.FieldRole, self.tab1_campaignComboBox)
    self.tab1_genderLabel = QtGui.QLabel("Gender", self.tab1_character_layout)
    self.tab1_genderLabel.setObjectName(_fromUtf8("tab1_genderLabel"))
    self.tab1_character_form.setWidget(3, QtGui.QFormLayout.LabelRole, self.tab1_genderLabel)
    self.tab1_genderComboBox = QtGui.QComboBox(self.tab1_character_layout)
    self.tab1_genderComboBox.activated.connect(self.character.setGender)
    self.tab1_genderComboBox.setObjectName(_fromUtf8("tab1_genderComboBox"))
    self.tab1_genderComboBox.addItem("Male")
    self.tab1_genderComboBox.addItem("Female")
    self.tab1_character_form.setWidget(3, QtGui.QFormLayout.FieldRole, self.tab1_genderComboBox)
    self.tab1_ageLabel = QtGui.QLabel("Age", self.tab1_character_layout)
    self.tab1_ageLabel.setObjectName(_fromUtf8("tab1_ageLabel"))
    self.tab1_character_form.setWidget(4, QtGui.QFormLayout.LabelRole, self.tab1_ageLabel)
    self.tab1_ageLineEdit = QtGui.QLineEdit(self.tab1_character_layout)
    self.tab1_ageLineEdit.textChanged.connect(self.character.setAge)
    self.tab1_ageLineEdit.setObjectName(_fromUtf8("tab1_ageLineEdit"))
    self.tab1_character_form.setWidget(4, QtGui.QFormLayout.FieldRole, self.tab1_ageLineEdit)
    self.tab1_heightLabel = QtGui.QLabel("Height", self.tab1_character_layout)
    self.tab1_heightLabel.setObjectName(_fromUtf8("tab1_heightLabel"))
    self.tab1_character_form.setWidget(5, QtGui.QFormLayout.LabelRole, self.tab1_heightLabel)
    self.tab1_heightLineEdit = QtGui.QLineEdit(self.tab1_character_layout)
    self.tab1_heightLineEdit.textChanged.connect(self.character.setHeight)
    self.tab1_heightLineEdit.setObjectName(_fromUtf8("tab1_heightLineEdit"))
    self.tab1_character_form.setWidget(5, QtGui.QFormLayout.FieldRole, self.tab1_heightLineEdit)
    self.tab1_weightLabel = QtGui.QLabel("Weight", self.tab1_character_layout)
    self.tab1_weightLabel.setObjectName(_fromUtf8("tab1_weightLabel"))
    self.tab1_character_form.setWidget(6, QtGui.QFormLayout.LabelRole, self.tab1_weightLabel)
    self.tab1_weightLineEdit = QtGui.QLineEdit(self.tab1_character_layout)
    self.tab1_weightLineEdit.textChanged.connect(self.character.setWeight)
    self.tab1_weightLineEdit.setObjectName(_fromUtf8("tab1_weightLineEdit"))
    self.tab1_character_form.setWidget(6, QtGui.QFormLayout.FieldRole, self.tab1_weightLineEdit)
    self.tab1_hairLabel = QtGui.QLabel("Hair", self.tab1_character_layout)
    self.tab1_hairLabel.setObjectName(_fromUtf8("tab1_hairLabel"))
    self.tab1_character_form.setWidget(7, QtGui.QFormLayout.LabelRole, self.tab1_hairLabel)
    self.tab1_hairLineEdit = QtGui.QLineEdit(self.tab1_character_layout)
    self.tab1_hairLineEdit.textChanged.connect(self.character.setHair)
    self.tab1_hairLineEdit.setObjectName(_fromUtf8("tab1_hairLineEdit"))
    self.tab1_character_form.setWidget(7, QtGui.QFormLayout.FieldRole, self.tab1_hairLineEdit)
    self.tab1_eyeslabel = QtGui.QLabel("Eyes", self.tab1_character_layout)
    self.tab1_eyeslabel.setObjectName(_fromUtf8("tab1_eyeslabel"))
    self.tab1_character_form.setWidget(8, QtGui.QFormLayout.LabelRole, self.tab1_eyeslabel)
    self.tab1_eyesLineEdit = QtGui.QLineEdit(self.tab1_character_layout)
    self.tab1_eyesLineEdit.textChanged.connect(self.character.setEyes)
    self.tab1_eyesLineEdit.setObjectName(_fromUtf8("tab1_eyesLineEdit"))
    self.tab1_character_form.setWidget(8, QtGui.QFormLayout.FieldRole, self.tab1_eyesLineEdit)
    self.tab1_experienceLabel = QtGui.QLabel("Experience", self.tab1_character_layout)
    self.tab1_experienceLabel.setObjectName(_fromUtf8("tab1_experienceLabel"))
    self.tab1_character_form.setWidget(10, QtGui.QFormLayout.LabelRole, self.tab1_experienceLabel)
    self.tab1_experienceSpinBox = QtGui.QSpinBox(self.tab1_character_layout)
    self.tab1_experienceSpinBox.valueChanged.connect(self.character.setExperience)
    self.tab1_experienceSpinBox.setMaximum(400000)
    self.tab1_experienceSpinBox.setObjectName(_fromUtf8("tab1_experienceSpinBox"))
    self.tab1_character_form.setWidget(10, QtGui.QFormLayout.FieldRole, self.tab1_experienceSpinBox)
    self.verticalLayout_22.addLayout(self.tab1_character_form)
        
    # Notable features
    self.tab1_features_layout = QtGui.QGroupBox("Notable Features", self.tab1_character_layout)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.tab1_features_layout.sizePolicy().hasHeightForWidth())
    self.tab1_features_layout.setSizePolicy(sizePolicy)
    self.tab1_features_layout.setObjectName(_fromUtf8("tab1_features_layout"))
    self.verticalLayout_21 = QtGui.QVBoxLayout(self.tab1_features_layout)
    self.verticalLayout_21.setObjectName(_fromUtf8("verticalLayout_21"))
    self.tab1_features = QtGui.QTextEdit(self.tab1_features_layout)
    self.tab1_features.textChanged.connect(self.notableFeaturesChanged)
    self.tab1_features.setObjectName(_fromUtf8("tab1_features"))
    self.verticalLayout_21.addWidget(self.tab1_features)
    self.verticalLayout_22.addWidget(self.tab1_features_layout)
    self.horizontalLayout_19.addWidget(self.tab1_character_layout)

    # image
    self.tab1_img_abilities_layout = QtGui.QVBoxLayout()
    self.tab1_img_abilities_layout.setContentsMargins(0, -1, -1, -1)
    self.tab1_img_abilities_layout.setObjectName(_fromUtf8("tab1_img_abilities_layout"))
    self.tab1_img_layout = QtGui.QHBoxLayout()
    self.tab1_img_layout.setObjectName(_fromUtf8("tab1_img_layout"))
    spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
    self.tab1_img_layout.addItem(spacerItem)
    self.tab1_img = QtGui.QLabel(self.tab1)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.tab1_img.sizePolicy().hasHeightForWidth())
    self.tab1_img.setSizePolicy(sizePolicy)
    self.tab1_img.setMaximumSize(QtCore.QSize(400, 400))
    self.tab1_img.setMinimumHeight(400)
    self.tab1_img.setText(_fromUtf8(""))
    self.tab1_img.setPixmap(QtGui.QPixmap("/home/loikki/Downloads/test.jpeg"))
    self.tab1_img.setScaledContents(True)
    self.tab1_img.setAlignment(QtCore.Qt.AlignCenter)
    self.tab1_img.setObjectName(_fromUtf8("tab1_img"))
    self.tab1_img_layout.addWidget(self.tab1_img)
    spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
    self.tab1_img_layout.addItem(spacerItem1)
    self.tab1_img_button_layout = QtGui.QVBoxLayout()
    self.tab1_img_button_layout.setObjectName(_fromUtf8("tab1_img_button_layout"))
    self.tab1_import_button = QtGui.QPushButton("Import Image", self.tab1)
    self.tab1_import_button.setObjectName(_fromUtf8("tab1_import_button"))
    self.tab1_import_button.clicked.connect(self.importImage)
    self.tab1_img_button_layout.addWidget(self.tab1_import_button)
    self.tab1_remove_button = QtGui.QPushButton("Remove Image", self.tab1)
    self.tab1_remove_button.setObjectName(_fromUtf8("tab1_remove_button"))
    self.tab1_remove_button.clicked.connect(self.removeImage)
    self.tab1_img_button_layout.addWidget(self.tab1_remove_button)
    self.tab1_img_layout.addLayout(self.tab1_img_button_layout)
    self.tab1_img_abilities_layout.addLayout(self.tab1_img_layout)
    
    # abilities
    self.tab1_abilities_layout = QtGui.QGroupBox("Abilities", self.tab1)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.tab1_abilities_layout.sizePolicy().hasHeightForWidth())
    self.tab1_abilities_layout.setSizePolicy(sizePolicy)
    self.tab1_abilities_layout.setObjectName(_fromUtf8("tab1_abilities_layout"))
    self.verticalLayout_19 = QtGui.QVBoxLayout(self.tab1_abilities_layout)
    self.verticalLayout_19.setSpacing(25)
    self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        
    # Choose Value
    self.tab1_ability_style_layout = QtGui.QHBoxLayout()
    self.tab1_ability_style_layout.setObjectName(_fromUtf8("tab1_ability_style_layout"))
    self.tab1_ability_style_combo = QtGui.QComboBox(self.tab1_abilities_layout)
    self.tab1_ability_style_combo.activated[str].connect(self.changeRollStyle)
    self.tab1_ability_style_combo.setMinimumSize(QtCore.QSize(120, 0))
    self.tab1_ability_style_combo.setObjectName(_fromUtf8("tab1_ability_style_combo"))
    self.tab1_ability_style_combo.addItem("Random")
    self.tab1_ability_style_combo.addItem("Free")
    self.tab1_ability_style_combo.addItem("Pregenerated")
    self.tab1_ability_style_combo.addItem("Points")
    self.tab1_ability_style_layout.addWidget(self.tab1_ability_style_combo)
    self.tab1_roll_button = QtGui.QPushButton("Roll", self.tab1_abilities_layout)
    self.tab1_roll_button.setObjectName(_fromUtf8("tab1_roll_button"))
    self.tab1_roll_button.clicked.connect(self.rollAbilities)
    self.tab1_ability_style_layout.addWidget(self.tab1_roll_button)
    self.tab1_ability_point_score = QtGui.QLabel("", self.tab1_abilities_layout)
    self.tab1_ability_style_layout.addWidget(self.tab1_ability_point_score)
    spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
    self.tab1_ability_style_layout.addItem(spacerItem2)
    self.verticalLayout_19.addLayout(self.tab1_ability_style_layout)

    # Show Value
    self.tab1_abilities_value_layout = QtGui.QHBoxLayout()
    self.tab1_abilities_value_layout.setObjectName(_fromUtf8("tab1_abilities_value_layout"))
    self.tab1_ability_value_1 = QtGui.QLineEdit(self.tab1_abilities_layout)
    self.tab1_ability_value_1.textChanged.connect(self.changeAbilityRoll)
    self.tab1_ability_value_1.setReadOnly(False)
    self.tab1_ability_value_1.setObjectName(_fromUtf8("tab1_ability_value_1"))
    self.tab1_abilities_value_layout.addWidget(self.tab1_ability_value_1)
    self.tab1_ability_value_2 = QtGui.QLineEdit(self.tab1_abilities_layout)
    self.tab1_ability_value_2.textChanged.connect(self.changeAbilityRoll)
    self.tab1_ability_value_2.setObjectName(_fromUtf8("tab1_ability_value_2"))
    self.tab1_abilities_value_layout.addWidget(self.tab1_ability_value_2)
    self.tab1_ability_value_3 = QtGui.QLineEdit(self.tab1_abilities_layout)
    self.tab1_ability_value_3.textChanged.connect(self.changeAbilityRoll)
    self.tab1_ability_value_3.setObjectName(_fromUtf8("tab1_ability_value_3"))
    self.tab1_abilities_value_layout.addWidget(self.tab1_ability_value_3)
    self.tab1_ability_value_4 = QtGui.QLineEdit(self.tab1_abilities_layout)
    self.tab1_ability_value_4.textChanged.connect(self.changeAbilityRoll)
    self.tab1_ability_value_4.setObjectName(_fromUtf8("tab1_ability_value_4"))
    self.tab1_abilities_value_layout.addWidget(self.tab1_ability_value_4)
    self.tab1_ability_value_5 = QtGui.QLineEdit(self.tab1_abilities_layout)
    self.tab1_ability_value_5.textChanged.connect(self.changeAbilityRoll)
    self.tab1_ability_value_5.setObjectName(_fromUtf8("tab1_ability_value_5"))
    self.tab1_abilities_value_layout.addWidget(self.tab1_ability_value_5)
    self.tab1_ability_value_6 = QtGui.QLineEdit(self.tab1_abilities_layout)
    self.tab1_ability_value_6.textChanged.connect(self.changeAbilityRoll)
    self.tab1_ability_value_6.setObjectName(_fromUtf8("tab1_ability_value_6"))
    self.tab1_abilities_value_layout.addWidget(self.tab1_ability_value_6)
    self.verticalLayout_19.addLayout(self.tab1_abilities_value_layout)

    # Score attribution
    self.tab1_abilities_choice_layout = QtGui.QGridLayout()
    self.tab1_abilities_choice_layout.setObjectName(_fromUtf8("tab1_abilities_choice_layout"))
    self.tab1_cha_combo = QtGui.QComboBox(self.tab1_abilities_layout)
    self.tab1_cha_combo.setObjectName(_fromUtf8("tab1_cha_combo"))
    self.tab1_cha_combo.activated[str].connect(self.character.setCharisma)
    self.tab1_cha_combo.activated.connect(self.changeAttributionAbility)
    self.tab1_abilities_choice_layout.addWidget(self.tab1_cha_combo, 1, 5, 1, 1)
    self.tab1_wis_combo = QtGui.QComboBox(self.tab1_abilities_layout)
    self.tab1_wis_combo.activated[str].connect(self.character.setWisdom)
    self.tab1_wis_combo.activated.connect(self.changeAttributionAbility)
    self.tab1_wis_combo.setObjectName(_fromUtf8("tab1_wis_combo"))
    self.tab1_abilities_choice_layout.addWidget(self.tab1_wis_combo, 1, 4, 1, 1)
    self.tab1_int_combo = QtGui.QComboBox(self.tab1_abilities_layout)
    self.tab1_int_combo.activated[str].connect(self.character.setIntelligence)
    self.tab1_int_combo.activated.connect(self.changeAttributionAbility)
    self.tab1_int_combo.setObjectName(_fromUtf8("tab1_int_combo"))
    self.tab1_abilities_choice_layout.addWidget(self.tab1_int_combo, 1, 3, 1, 1)
    self.tab1_con_combo = QtGui.QComboBox(self.tab1_abilities_layout)
    self.tab1_con_combo.activated[str].connect(self.character.setConstitution)
    self.tab1_con_combo.activated.connect(self.changeAttributionAbility)
    self.tab1_con_combo.setObjectName(_fromUtf8("tab1_con_combo"))
    self.tab1_abilities_choice_layout.addWidget(self.tab1_con_combo, 1, 2, 1, 1)
    self.tab1_dex_combo = QtGui.QComboBox(self.tab1_abilities_layout)
    self.tab1_dex_combo.activated[str].connect(self.character.setDexterity)
    self.tab1_dex_combo.activated.connect(self.changeAttributionAbility)
    self.tab1_dex_combo.setObjectName(_fromUtf8("tab1_dex_combo"))
    self.tab1_abilities_choice_layout.addWidget(self.tab1_dex_combo, 1, 1, 1, 1)
    self.tab1_str_combo = QtGui.QComboBox(self.tab1_abilities_layout)
    self.tab1_str_combo.activated[str].connect(self.character.setStrength)
    self.tab1_str_combo.activated.connect(self.changeAttributionAbility)
    self.tab1_str_combo.setObjectName(_fromUtf8("tab1_str_combo"))
    self.tab1_abilities_choice_layout.addWidget(self.tab1_str_combo, 1, 0, 1, 1)
    # labels
    self.tab1_cha_label = QtGui.QLabel("Charisma", self.tab1_abilities_layout)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.tab1_cha_label.sizePolicy().hasHeightForWidth())
    self.tab1_cha_label.setSizePolicy(sizePolicy)
    self.tab1_cha_label.setAlignment(QtCore.Qt.AlignCenter)
    self.tab1_cha_label.setObjectName(_fromUtf8("tab1_cha_label"))
    self.tab1_abilities_choice_layout.addWidget(self.tab1_cha_label, 0, 5, 1, 1)
    self.tab1_wis_label = QtGui.QLabel("Wisdom", self.tab1_abilities_layout)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.tab1_wis_label.sizePolicy().hasHeightForWidth())
    self.tab1_wis_label.setSizePolicy(sizePolicy)
    self.tab1_wis_label.setAlignment(QtCore.Qt.AlignCenter)
    self.tab1_wis_label.setObjectName(_fromUtf8("tab1_wis_label"))
    self.tab1_abilities_choice_layout.addWidget(self.tab1_wis_label, 0, 4, 1, 1)
    self.tab1_str_label = QtGui.QLabel("Strength", self.tab1_abilities_layout)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.tab1_str_label.sizePolicy().hasHeightForWidth())
    self.tab1_str_label.setSizePolicy(sizePolicy)
    self.tab1_str_label.setAlignment(QtCore.Qt.AlignCenter)
    self.tab1_str_label.setObjectName(_fromUtf8("tab1_str_label"))
    self.tab1_abilities_choice_layout.addWidget(self.tab1_str_label, 0, 0, 1, 1)
    self.tab1_dex_label = QtGui.QLabel("Dexterity", self.tab1_abilities_layout)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.tab1_dex_label.sizePolicy().hasHeightForWidth())
    self.tab1_dex_label.setSizePolicy(sizePolicy)
    self.tab1_dex_label.setAlignment(QtCore.Qt.AlignCenter)
    self.tab1_dex_label.setObjectName(_fromUtf8("tab1_dex_label"))
    self.tab1_abilities_choice_layout.addWidget(self.tab1_dex_label, 0, 1, 1, 1)
    self.tab1_con_label = QtGui.QLabel("Constitution", self.tab1_abilities_layout)
    self.tab1_con_label.setAlignment(QtCore.Qt.AlignCenter)
    self.tab1_con_label.setObjectName(_fromUtf8("tab1_con_label"))
    self.tab1_abilities_choice_layout.addWidget(self.tab1_con_label, 0, 2, 1, 1)
    self.tab1_int_label = QtGui.QLabel("Intelligence", self.tab1_abilities_layout)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.tab1_int_label.sizePolicy().hasHeightForWidth())
    self.tab1_int_label.setSizePolicy(sizePolicy)
    self.tab1_int_label.setAlignment(QtCore.Qt.AlignCenter)
    self.tab1_int_label.setObjectName(_fromUtf8("tab1_int_label"))
    self.tab1_abilities_choice_layout.addWidget(self.tab1_int_label, 0, 3, 1, 1)
    self.verticalLayout_19.addLayout(self.tab1_abilities_choice_layout)
    spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
    self.verticalLayout_19.addItem(spacerItem3)
    self.tab1_img_abilities_layout.addWidget(self.tab1_abilities_layout)
    self.horizontalLayout_19.addLayout(self.tab1_img_abilities_layout)
    self.main_tab.addTab(self.tab1, "Description")
