from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s


def setupCharacterChoice(self):
    # create tab
    self.tab0 = QtGui.QWidget()
    self.tab0.setObjectName(_fromUtf8("tab0"))
    self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tab0)
    self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))

    # create character choice tree
    self.tab0_character_choice_layout = QtGui.QVBoxLayout()
    self.tab0_character_choice_layout.setObjectName(_fromUtf8("tab0_character_choice_layout"))
    self.tab0_character_choice = QtGui.QListWidget(self.tab0)
    self.tab0_character_choice.currentRowChanged.connect(self.printSummary)
    self.tab0_character_choice.setSortingEnabled(False)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.tab0_character_choice.sizePolicy().hasHeightForWidth())
    self.tab0_character_choice.setSizePolicy(sizePolicy)
    self.tab0_character_choice.setObjectName(_fromUtf8("tab0_character_choice"))

    # add the list
    self.tab0_character_choice_layout.addWidget(self.tab0_character_choice)

    # create buttons
    self.tab0_button_layout = QtGui.QHBoxLayout()
    self.tab0_button_layout.setObjectName(_fromUtf8("tab0_button_layout"))
    self.tab0_new_character = QtGui.QPushButton("New Character", self.tab0)
    self.tab0_new_character.clicked.connect(self.newCharacter)
    self.tab0_new_character.setObjectName(_fromUtf8("tab0_new_character"))
    self.tab0_button_layout.addWidget(self.tab0_new_character)
    self.tab0_choose_current = QtGui.QPushButton("Choose Current Character", self.tab0)
    self.tab0_choose_current.setObjectName(_fromUtf8("tab0_choose_current"))
    self.tab0_choose_current.clicked.connect(self.loadCharacter)
    self.tab0_button_layout.addWidget(self.tab0_choose_current)
    self.tab0_character_choice_layout.addLayout(self.tab0_button_layout)

    # create summary part
    self.horizontalLayout_2.addLayout(self.tab0_character_choice_layout)
    self.tab0_summary_layout = QtGui.QGroupBox("Summary", self.tab0)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.tab0_summary_layout.sizePolicy().hasHeightForWidth())

    # create class/background/race part
    self.tab0_summary_layout.setSizePolicy(sizePolicy)
    self.tab0_summary_layout.setObjectName(_fromUtf8("tab0_summary_layout"))
    self.verticalLayout_17 = QtGui.QVBoxLayout(self.tab0_summary_layout)
    self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
    self.tab0_img_background_layout = QtGui.QHBoxLayout()
    self.tab0_img_background_layout.setContentsMargins(-1, 0, -1, -1)
    self.tab0_img_background_layout.setObjectName(_fromUtf8("tab0_img_background_layout"))
    self.tab0_background_layout = QtGui.QFormLayout()
    self.tab0_background_layout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
    self.tab0_background_layout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
    self.tab0_background_layout.setObjectName(_fromUtf8("tab0_background_layout"))
    self.tab0_classLabel_2 = QtGui.QLabel("Class", self.tab0_summary_layout)
    self.tab0_classLabel_2.setObjectName(_fromUtf8("tab0_classLabel_2"))
    self.tab0_background_layout.setWidget(0, QtGui.QFormLayout.LabelRole, self.tab0_classLabel_2)
    self.tab0_classLineEdit = QtGui.QLineEdit(self.tab0_summary_layout)
    self.tab0_classLineEdit.setReadOnly(True)
    self.tab0_classLineEdit.setObjectName(_fromUtf8("tab0_classLineEdit"))
    self.tab0_background_layout.setWidget(0, QtGui.QFormLayout.FieldRole, self.tab0_classLineEdit)
    self.tab0_raceLineEdit = QtGui.QLineEdit(self.tab0_summary_layout)
    self.tab0_raceLineEdit.setReadOnly(True)
    self.tab0_raceLineEdit.setObjectName(_fromUtf8("tab0_raceLineEdit"))
    self.tab0_background_layout.setWidget(1, QtGui.QFormLayout.FieldRole, self.tab0_raceLineEdit)
    self.tab0_specializationLabel_2 = QtGui.QLabel("Specialization", self.tab0_summary_layout)
    self.tab0_specializationLabel_2.setObjectName(_fromUtf8("tab0_specializationLabel_2"))
    self.tab0_background_layout.setWidget(2, QtGui.QFormLayout.LabelRole, self.tab0_specializationLabel_2)
    self.tab0_specializationLineEdit = QtGui.QLineEdit(self.tab0_summary_layout)
    self.tab0_specializationLineEdit.setReadOnly(True)
    self.tab0_specializationLineEdit.setObjectName(_fromUtf8("tab0_specializationLineEdit"))
    self.tab0_background_layout.setWidget(2, QtGui.QFormLayout.FieldRole, self.tab0_specializationLineEdit)
    self.tab0_raceLabel = QtGui.QLabel("Race", self.tab0_summary_layout)
    self.tab0_raceLabel.setObjectName(_fromUtf8("tab0_raceLabel"))
    self.tab0_background_layout.setWidget(1, QtGui.QFormLayout.LabelRole, self.tab0_raceLabel)
    self.tab0_backgroundLabel = QtGui.QLabel("Background", self.tab0_summary_layout)
    self.tab0_backgroundLabel.setObjectName(_fromUtf8("tab0_backgroundLabel"))
    self.tab0_background_layout.setWidget(3, QtGui.QFormLayout.LabelRole, self.tab0_backgroundLabel)
    self.tab0_backgroundLineEdit = QtGui.QLineEdit(self.tab0_summary_layout)
    self.tab0_backgroundLineEdit.setReadOnly(True)
    self.tab0_backgroundLineEdit.setObjectName(_fromUtf8("tab0_backgroundLineEdit"))
    self.tab0_background_layout.setWidget(3, QtGui.QFormLayout.FieldRole, self.tab0_backgroundLineEdit)
    self.tab0_experienceLevelLabel = QtGui.QLabel("Experience (Level)", self.tab0_summary_layout)
    self.tab0_experienceLevelLabel.setObjectName(_fromUtf8("tab0_experienceLevelLabel"))
    self.tab0_background_layout.setWidget(4, QtGui.QFormLayout.LabelRole, self.tab0_experienceLevelLabel)
    self.tab0_experienceLevelLineEdit = QtGui.QLineEdit(self.tab0_summary_layout)
    self.tab0_experienceLevelLineEdit.setReadOnly(True)
    self.tab0_experienceLevelLineEdit.setObjectName(_fromUtf8("tab0_experienceLevelLineEdit"))
    self.tab0_background_layout.setWidget(4, QtGui.QFormLayout.FieldRole, self.tab0_experienceLevelLineEdit)

    # create image
    self.tab0_img_background_layout.addLayout(self.tab0_background_layout)
    self.tab0_img = QtGui.QLabel(self.tab0_summary_layout)
    self.tab0_img.setMaximumSize(QtCore.QSize(150, 150))
    self.tab0_img.setText(_fromUtf8(""))
    self.tab0_img.setPixmap(QtGui.QPixmap(_fromUtf8("/home/loikki/Downloads/test.jpeg")))
    self.tab0_img.setScaledContents(True)
    self.tab0_img.setObjectName(_fromUtf8("tab0_img"))
    self.tab0_img_background_layout.addWidget(self.tab0_img)
    
    # create ability layout
    self.verticalLayout_17.addLayout(self.tab0_img_background_layout)
    self.tab0_ability_layout = QtGui.QGridLayout()
    self.tab0_ability_layout.setObjectName(_fromUtf8("tab0_ability_layout"))
    self.tab0_dex_label = QtGui.QLabel("Dexterity", self.tab0_summary_layout)
    self.tab0_dex_label.setAlignment(QtCore.Qt.AlignCenter)
    self.tab0_dex_label.setObjectName(_fromUtf8("tab0_dex_label"))
    self.tab0_ability_layout.addWidget(self.tab0_dex_label, 0, 1, 1, 1)
    self.tab0_con_label = QtGui.QLabel("Constitution", self.tab0_summary_layout)
    self.tab0_con_label.setAlignment(QtCore.Qt.AlignCenter)
    self.tab0_con_label.setObjectName(_fromUtf8("tab0_con_label"))
    self.tab0_ability_layout.addWidget(self.tab0_con_label, 0, 2, 1, 1)
    self.tab0_int_label = QtGui.QLabel("Intelligence", self.tab0_summary_layout)
    self.tab0_int_label.setAlignment(QtCore.Qt.AlignCenter)
    self.tab0_int_label.setObjectName(_fromUtf8("tab0_int_label"))
    self.tab0_ability_layout.addWidget(self.tab0_int_label, 0, 3, 1, 1)
    self.tab0_wis_label = QtGui.QLabel("Wisdom", self.tab0_summary_layout)
    self.tab0_wis_label.setAlignment(QtCore.Qt.AlignCenter)
    self.tab0_wis_label.setObjectName(_fromUtf8("tab0_wis_label"))
    self.tab0_ability_layout.addWidget(self.tab0_wis_label, 0, 4, 1, 1)
    self.tab0_cha_label = QtGui.QLabel("Charisma", self.tab0_summary_layout)
    self.tab0_cha_label.setAlignment(QtCore.Qt.AlignCenter)
    self.tab0_cha_label.setObjectName(_fromUtf8("tab0_cha_label"))
    self.tab0_ability_layout.addWidget(self.tab0_cha_label, 0, 5, 1, 1)
    self.tab0_str_label = QtGui.QLabel("Strength", self.tab0_summary_layout)
    self.tab0_str_label.setAlignment(QtCore.Qt.AlignCenter)
    self.tab0_str_label.setObjectName(_fromUtf8("tab0_str_label"))
    self.tab0_ability_layout.addWidget(self.tab0_str_label, 0, 0, 1, 1)
    self.tab0_str_value = QtGui.QLabel("12", self.tab0_summary_layout)
    self.tab0_str_value.setAlignment(QtCore.Qt.AlignCenter)
    self.tab0_str_value.setObjectName(_fromUtf8("tab0_str_value"))
    self.tab0_ability_layout.addWidget(self.tab0_str_value, 1, 0, 1, 1)
    self.tab0_dex_value = QtGui.QLabel("10", self.tab0_summary_layout)
    self.tab0_dex_value.setAlignment(QtCore.Qt.AlignCenter)
    self.tab0_dex_value.setObjectName(_fromUtf8("tab0_dex_value"))
    self.tab0_ability_layout.addWidget(self.tab0_dex_value, 1, 1, 1, 1)
    self.tab0_con_value = QtGui.QLabel("9", self.tab0_summary_layout)
    self.tab0_con_value.setAlignment(QtCore.Qt.AlignCenter)
    self.tab0_con_value.setObjectName(_fromUtf8("tab0_con_value"))
    self.tab0_ability_layout.addWidget(self.tab0_con_value, 1, 2, 1, 1)
    self.tab0_int_value = QtGui.QLabel("16", self.tab0_summary_layout)
    self.tab0_int_value.setAlignment(QtCore.Qt.AlignCenter)
    self.tab0_int_value.setObjectName(_fromUtf8("tab0_int_value"))
    self.tab0_ability_layout.addWidget(self.tab0_int_value, 1, 3, 1, 1)
    self.tab0_wis_value = QtGui.QLabel("8", self.tab0_summary_layout)
    self.tab0_wis_value.setAlignment(QtCore.Qt.AlignCenter)
    self.tab0_wis_value.setObjectName(_fromUtf8("tab0_wis_value"))
    self.tab0_ability_layout.addWidget(self.tab0_wis_value, 1, 4, 1, 1)
    self.tab0_cha_value = QtGui.QLabel("11", self.tab0_summary_layout)
    self.tab0_cha_value.setAlignment(QtCore.Qt.AlignCenter)
    self.tab0_cha_value.setObjectName(_fromUtf8("tab0_cha_value"))
    self.tab0_ability_layout.addWidget(self.tab0_cha_value, 1, 5, 1, 1)
    self.verticalLayout_17.addLayout(self.tab0_ability_layout)

    # proficiencies
    self.tab0_proficiencies_layout = QtGui.QGroupBox("Proficiencies", self.tab0_summary_layout)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.tab0_proficiencies_layout.sizePolicy().hasHeightForWidth())
    self.tab0_proficiencies_layout.setSizePolicy(sizePolicy)
    self.tab0_proficiencies_layout.setObjectName(_fromUtf8("tab0_proficiencies_layout"))
    self.horizontalLayout_42 = QtGui.QHBoxLayout(self.tab0_proficiencies_layout)
    self.horizontalLayout_42.setObjectName(_fromUtf8("horizontalLayout_42"))
    
    # saving throws
    self.tab0_list_saving = []
    self.tab0_saving_skill_layout = QtGui.QVBoxLayout()
    self.tab0_saving_skill_layout.setObjectName(_fromUtf8("tab0_saving_skill_layout"))
    self.tab0_saving_layout = QtGui.QGroupBox("Saving Throws", self.tab0_proficiencies_layout)
    self.tab0_saving_layout.setObjectName(_fromUtf8("tab0_saving_layout"))
    self.hLayout_saving = QtGui.QHBoxLayout(self.tab0_saving_layout)
    self.hLayout_saving.setObjectName(_fromUtf8("hLayout_saving"))
    self.tab0_saving_skill_layout.addWidget(self.tab0_saving_layout)

    # skill
    self.tab0_list_skill = []
    self.tab0_skill_layout = QtGui.QGroupBox("Skills", self.tab0_proficiencies_layout)
    self.tab0_skill_layout.setObjectName(_fromUtf8("tab0_skill_layout"))
    self.gridLayout_15 = QtGui.QGridLayout(self.tab0_skill_layout)
    self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
    self.tab0_saving_skill_layout.addWidget(self.tab0_skill_layout)
    self.horizontalLayout_42.addLayout(self.tab0_saving_skill_layout)

    # Object proficiencies
    self.tab0_list_object = []
    self.tab0_object_proficiency_layout = QtGui.QGroupBox("Objects", self.tab0_proficiencies_layout)
    self.tab0_object_proficiency_layout.setObjectName(_fromUtf8("tab0_object_proficiency_layout"))
    self.gridLayout_16 = QtGui.QGridLayout(self.tab0_object_proficiency_layout)
    self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
    self.horizontalLayout_42.addWidget(self.tab0_object_proficiency_layout)
    self.verticalLayout_17.addWidget(self.tab0_proficiencies_layout)
    self.horizontalLayout_2.addWidget(self.tab0_summary_layout)
    self.main_tab.addTab(self.tab0, "Character Choice")

    self.main_tab.currentChanged.connect(self.loadListCharacters)
    self.loadListCharacters()
